### ISSUE TITLE
Refine Arm Teensy Control

### ISSUE THREAD

**Issue by vashmata** [space-concordia-robotics/robotics-prototype#100]
### Refined motor control
- [ ] open loop
- - [ ] Implement speed profiles (not sure if I need to do this)
- - [ ] Automatically increase error based on position of arm joints in order to take arm weight into account
- [ ] closed loop
- - [ ] Tune PIDs (fine-tuning can be put on hold as it works regardless)
- - [x] Determine correct gear ratios and multipliers (necessary for doing inverse kinematics properly but does not involve changing the structure of the code)
- - [ ] Determine the correct angle limits of all arm joints

## Varia
- [x] Make new blink pattern during continuous commands like budge
- - [x] blink differently during budge
- - [x] confirm that when ignoring empty strings, special budge pattern works
- [x] Watchdog timer: reboot if an infinite loop occurs, freezing the microcontroller
- - [x] Implement watchdog timer code
- - [x] Decide where to use watchdog code and place it there
- [ ] Save angles to memory when microcontroller is to be shut off and load them when microcontroller is turned back on
- [ ] Implement Teensy bootup sequence
## Communications
- [ ] Settle on list of commands (in progress)
- [x] Listen for a variety of commands and responds appropriately to them:
- - [x] Control motors: stop, move to angle, budge, home, reset angle value
- - [x] Adjust parameters: motor speed, arm speed, open loop gain, PID gains, gear ratio...
- - [x] Change modes: switch between open and closed loop, switch direction logic, software reboot
- - [ ] Enable or disable debugging (not sure if I want to do this anymore)
- [x] Validate commands to ensure that the inputs are correct
- [x] Respond to the inputs to execute the commands
- [ ] Make ROSserial work on Teensy (in progress, this should be a separate issue for later)
- - [ ] Implement ROSserial (in progress, this should be a separate issue for later)

**Comment by PeterGhimself** [comment]
@vashmata this issue seems pretty big. Can we make this an epic and break it down into issues?

**Comment by MartensCedric** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Refine Arm Teensy Control](https://trello.com/c/pG3Tb8oi/156-refine-arm-teensy-control)

**Comment by vashmata** [comment]
> @vashmata this issue seems pretty big. Can we make this an epic and break it down into issues?

Yes
