### ISSUE TITLE
Joystick Controls

### ISSUE THREAD

**Issue by PeterGhimself** [space-concordia-robotics/robotics-prototype#108]
Demo to connect controlling any type of motor with arduino over ROS network using a joy stick controller such as XBOX 360/PS3.
Good place to start [here](https://github.com/space-concordia-robotics/robotics-prototype/tree/master/robot/rospackages/src/robot_teleop_joy).

## Checklist
- [x] Wheels control
- - [x] Prototype code
- - [x] Testing the prototype code
- - [x] Optimize the code
- - [x] Implement and test camera servo controls
- - [x] Final testing
- [x] Arm control
- - [x] Prototype code
- - [x] Implement and test forward kinematics controls
- - [x] Implement and test stop and reset buttons
- - ~~[ ] Implement and test inverse kinematics controls~~
- - [x] Testing
- ~~[ ] Cameras control~~
- - ~~[ ] Implement button to take pictures?~~
- ~~[ ] Drill Controls ~~
- [x] Switch between modules
- - [x] switch between arm and wheels
- - ~~[ ] add other types of switching~~

**Comment by Waleed-HM** [comment]
I changed the name to Joystick Controls only because I will also be doing arm and camera controls using the joystick

**Comment by PeterGhimself** [comment]
Renaming back so as to keep this task more granular, another issue for joy stick arm controls will be made.

**Comment by PeterGhimself** [comment]
Created and pushed branch [joystick-wheel-control-108](/space-concordia-robotics/robotics-prototype/tree/joystick-wheel-control-108) for this issue.
