### ISSUE TITLE
Rover Status LED

### ISSUE THREAD

**Issue by PeterGhimself** [space-concordia-robotics/robotics-prototype#112]
Using Odroid GPIO pins, have certain LED patterns to indicate readiness/different states.

MVP:
- [ ] A process to monitor that a list of rover ROS nodes are running.
- [ ] Distinguish between which rover nodes are active

Extra:
- Check on base station connection/ROS nodes (if this is even useful)
- Check connection to MCUs (which node is running, if said MCU is "activated" --> use "who" serial cmd to query)

**Comment by PeterGhimself** [comment]
We need to redefine the reqs here based off the new rules for ERC _and_ URC 2020

**Comment by PeterGhimself** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [A14.5 LED Control Module](https://trello.com/c/rdBV7ueV/157-a145-led-control-module)

**Comment by PeterGhimself** [comment]
@KoaTheKoala just to clarify. This task (for URC 2020) should cause the LED only to flash when we've reached the target at the end of a leg during autonomous traversal, correct? Because previously I had interpreted the competition rules to mean that when the autonomy task would start and we would run certain nodes _then_ to indicate that we are driving autonomously with the use of this LED.

**Comment by MartensCedric** [comment]
@PeterGhimself Is the description of this issue still accurate
