### ISSUE TITLE
LLC functional test

### ISSUE THREAD

**Issue by PeterGhimself** [space-concordia-robotics/robotics-prototype#114]
Code to facilitate testing for MUX LLC failures.

Script for Odroid:
1. Send TX data of "{currentChannel},OK", once response received over RX log data to file including message sent, received and time stamps for both
2. Repeat above for all channels

Sketch for Teensy:
1. Listen to RX (check if serial1,2,3,4 available)
2. If RX data available, print data to USB of "{currentChannel},OK", include timestamp if possible
3. Send TX "{currentChannel,OK}"

**Comment by vashmata** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Automate MUX Test](https://trello.com/c/VufBVxr4/20-automate-mux-test)

**Comment by PeterGhimself** [comment]
This is less relevant now that we are going to move away from UART, however for now the PDS is still using UART to communicate with the odroid and all that remains to be done is for this code to be properly tested. Having a functional test for the LLC/mux board wouldn't hurt.

**Comment by PeterGhimself** [comment]
For convenience we should make sure that we have a spare:
- [ ] Odroid
- [ ] eMMC/SD card with good image
- [ ] At least 2 teensies

**Comment by vashmata** [comment]
> This is less relevant now that we are going to move away from UART, however for now the PDS is still using UART to communicate with the odroid

Given that we won't be switching mux channels anymore I believe it is better to leave this and focus on new tasks.

**Comment by PeterGhimself** [comment]
@vashmata I agree but since for legacy reasons we have 4 options, we can see them as redundancies... could be helpful to switch if something breaks and we have no time for a proper fix and have to hack it on the spot?
Although to be fair this test was meant to be more of an endurance test if I remember correctly... it was @abting 's idea after all :grinning:
