### ISSUE TITLE
PDS integration

### ISSUE THREAD

**Issue by PeterGhimself** [space-concordia-robotics/robotics-prototype#117]
Linking the current PDS to the GUI through ROS, adding controls/feedback.
The PDS is able to report: battery voltage, rover wheel currents (6), and temperatures (3)

- [x] Create ROS node to listen to PDS and publish to topic for GUI to use
- - [x] create the node
- - [x] the node can parse data from the PDS:
- - - [x] Fix bugs in PDS code if necessary
- - - - [x] Fix bug where PDS stops sending feedback
- - - - [x] Add responses to all PDS commands
- - - - [x] Add 'who' command
- - - - [x] Ensure proper error handling of all commands sent to PDS: (sending strings instead of numbers, not sending a number defaults to 0, motor number too high or too low, other types of bugs)
- - - - [x] Reformat PDS node based on new message format from MCU code
- - [x] the node can publish data from the PDS:
- - - [x] /battery_voltage is 
- - - [x] /wheel_motor_currents is JointState, placed in `effort` array
- - - [x] /battery_temps is Point with 3 values as x y z
- [x] Integration test of the above (use ros bash cmds to verify)
- [x] Add PDS feedback visualization to GUI wherever necessary
- - [x] Update wheel motor currents in wheel motor table
- - [x] Update battery voltage in navbar
- - [x] Find a place to display the 3 battery temperatures
- [x] Add control cmds to GUI
- [x] Final integration test

This issue will close issue https://github.com/space-concordia-robotics/robotics-prototype/issues/17

**Comment by vashmata** [comment]
The issue https://github.com/space-concordia-robotics/robotics-prototype/issues/17 relates to this issue. The motor table which is supposed to display the motor currents exists inside the rover webpage.

**Comment by vashmata** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [PDS -> GUI Implementation](https://trello.com/c/YdBibq1o/54-pds-gui-implementation)
