### ISSUE TITLE
Camera Servo Control

### ISSUE THREAD

**Issue by PeterGhimself** [space-concordia-robotics/robotics-prototype#119]
At URC _some_ stuff worked, but most didn't.
Side note: position servos labelled as tilt, continuous rotation servos labelled as pan

- [x] Implement control of continuous/position servos in gui
- [x] Link camera servo code to front servos and test
- [x] Check if out of control issues are still there (pro-tip: stop position might be 93, not 90)
- [x] Link camera servo code to rear servos and test
- [x] Determine and hardcode angle limits for position servos
- [ ] Integration test of all servo control code
- ~~[ ] Ensure that once the rover_listener is activated it sends a stop command to continuous servos (commands are already there but probably not in the right place)~~ fixed in the MCU as it should be
- ~~[ ] Should we keep the homing option? if so, should we have an input box to choose the home position?~~ meh
- ~~[ ] Should we keep the input box control for the servos?~~ meh
- ~~[ ] should the servo limits be user-settable the way the rover limits are?~~ meh

**Comment by vashmata** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Camera Servo Control](https://trello.com/c/RVW9xjY7/56-camera-servo-control)

**Comment by vashmata** [comment]
Closed by #158
