### ISSUE TITLE
Arm Position

### ISSUE THREAD

**Issue by PeterGhimself** [space-concordia-robotics/robotics-prototype#12]

**Comment by PeterGhimself** [comment]
@vashmata do you think any more issues fall under this Epic? So far we just have #134
By the way if you aren't then use Zenhub chrome extension to see the epics and stuff that otherwise is not available in github

**Comment by vashmata** [comment]
I'm not sure what arm position means

**Comment by PeterGhimself** [comment]
@vashmata Arm Vision was meant to indicate the use of camera vision

**Comment by PeterGhimself** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [A2.3 Simulation](https://trello.com/c/Cd26FwSj/144-a23-simulation)

**Comment by vashmata** [comment]
> @vashmata do you think any more issues fall under this Epic? So far we just have #134

Yes, issue #278 now relates to this epic
