### ISSUE TITLE
Base station launch desktop icon

### ISSUE THREAD

**Issue by PeterGhimself** [space-concordia-robotics/robotics-prototype#121]
Currently to launch the base station, we need to run `./app.py`, as well as `roslaunch rosbridge_server rosbridge_websocket.launch` (making sure to deactivate venv for the second command).

Pro-tip: After the first part works, you can use `ps aux | grep <keyword>` to find the process id, and kill it with `kill -9 <process_id>`

- [ ] Create icon to run above commands in one shot
- - [ ] Ensuring a way of killing processes gracefully on exit
- [ ] (Super nice to have) Piping the output of the above commands either to a log file or some other console

**Comment by vashmata** [comment]
Side note, we have officially merged a sample `.bash_aliases` file inside `/basestation/config` which holds two aliases for the above commands. `startgui` runs the flask server (app.py) and `rosgui` runs the ROS websocket server (runs the launch file)

**Comment by vashmata** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Desktop shortcut to launch the GUI](https://trello.com/c/W3faT0kJ/122-desktop-shortcut-to-launch-the-gui)

**Comment by vashmata** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Base station Launch Icon](https://trello.com/c/hV7HuuiC/98-base-station-launch-icon)

**Comment by MartensCedric** [comment]
todo for me (Cedric) : Unmerge the ROS3d branch

F

**Comment by MartensCedric** [comment]
Putting this on hold until there's a resolution with the rosbridge/venv issue
