### ISSUE TITLE
Atom linter bug

### ISSUE THREAD

**Issue by KoaTheKoala** [space-concordia-robotics/robotics-prototype#124]
Environment info:
-Running on Ubuntu 16.04

Steps to reproduce:
1) Navigate to project root (robotics-prototype)
2) Activate venv
3) Open Atom
4) In atom, open the project folder (File -> Open File -> robotics-prototype)
---> this is where Atom pops up that an error has occurred. You can view the specific error by going to View -> Developer -> Toggle Developer Tools. From here open the console tab.

Expected output:
No errors

Actual output:
?

Error messages:
![image](https://user-images.githubusercontent.com/22074181/61998241-233a4c80-b07b-11e9-8a93-de3d74c51ecf.png)

**Comment by MartensCedric** [comment]
Closing because "we dont care about atom"
