### ISSUE TITLE
ROS requests generated in the GUI do not time out

### ISSUE THREAD

**Issue by vashmata** [space-concordia-robotics/robotics-prototype#129]
Note that this is low priority. ROS was integrated into the GUI via a javascript library called roslibjs. The person in charge of integrating this is not familiar enough with javascript and jquery to know how to handle timeouts. The result of this is that whenever the GUI generates a request, if there is no response then there will be no feedback in the GUI. What /should/ occur is that after a certain timeout, say 75ms, the GUI should indicate that no response has come from ROS.

**Comment by vashmata** [comment]
by the way that someone is me

**Comment by MartensCedric** [comment]
As discussed, 75ms may not be enough
