### ISSUE TITLE
Link inverse kinematics to arm MCU

### ISSUE THREAD

**Issue by vashmata** [space-concordia-robotics/robotics-prototype#132]
Inverse kinematics calculations already function and a node exists, but the GUI has no way to request the calculations or send the results to the arm MCU. The arm also needs to have the correct angle calculations.

- [ ] Add guide to running IK stuff somewhere
- [x] The inverse kinematics calculator from branch/issue 91 was adjusted in branch 105
- [x] A ROS node was also created in branch 105
- [ ] Adjust variables in arm MCU code to get proper angle calculations
- [ ] (should potentially do this in a different branch) confirm that homing code works and use it for angle calculations
- [ ] Retest inverse kinematics ROS node and calculator to confirm they work
- [ ] Add inverse kinematics controls to GUI
- - [ ] while button is being pressed, send a new command every x ms
- - [ ] each command increments the request by y metres or z radians/degrees
- - [ ] there is an input to control the increment for increasing/decreasing speed...must play well with armspeed
- - [ ] Make sure that switching between manual and auto works fine
- [ ] Link said controls to ROS
- [ ] Test the arm controls and adjust parameters

Once IK control is linked in the GUI, it will close issues https://github.com/space-concordia-robotics/robotics-prototype/issues/27 and https://github.com/space-concordia-robotics/robotics-prototype/issues/25
Kind of relates to https://github.com/space-concordia-robotics/robotics-prototype/issues/66 except we decided to use our own script.

**Comment by vashmata** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Inverse Kinematics](https://trello.com/c/zaDPo6r7/22-inverse-kinematics)

**Comment by PeterGhimself** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [A2.2 Homing and Inverse Kinematics](https://trello.com/c/gfcSHcZL/143-a22-homing-and-inverse-kinematics)
