### ISSUE TITLE
Centralize the check for the time since last command

### ISSUE THREAD

**Issue by MartensCedric** [space-concordia-robotics/robotics-prototype#142]
Right now the time since last command is checked is the responsibility of the function calling it. This change would delegate the responsibility to the ros helper actually sending the command.

**Comment by vashmata** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fully implement local mode software setup](https://trello.com/c/it68DGPN/121-fully-implement-local-mode-software-setup)

**Comment by PeterGhimself** [comment]
Deleted a dead link to a non-existing Trello card (which did not seem related to this issue)
