### ISSUE TITLE
Decouple RequestTask from GUI

### ISSUE THREAD

**Issue by MartensCedric** [space-concordia-robotics/robotics-prototype#145]
The current method signature `function requestTask (reqTask, reqStatus, buttonID, callback, reqArgs = '')`

Can be reduced to a smaller signature
`function requestTask (reqTask, reqStatus, callback, reqArgs = '')`

The reqStatus and button ID removal will allow much cleaner code (See camera streams and other use cases)

**Comment by PeterGhimself** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Develop simple autonomous traversal algorithm](https://trello.com/c/J6kOSido/99-develop-simple-autonomous-traversal-algorithm)

**Comment by vashmata** [comment]
We discussed this in person but `reqStatus` is still required. Perhaps it could be combined with `reqArgs` however.

**Comment by MartensCedric** [comment]
- [ ] Decouple GUI with communication layer
- [ ] Reduce number of arguments
- [ ] Document the function
- [ ] Remove magic numbers
- [ ] Keep functions small
