### ISSUE TITLE
Obtain the linear velocity of the rover

### ISSUE THREAD

**Issue by MartensCedric** [space-concordia-robotics/robotics-prototype#150]
Using the PX4FLOW Smart Camera, obtain the linear velocity of the rover. 

According to this table : https://docs.px4.io/v1.9.0/en/sensor/px4flow.html#optics
and some extrapolation, I estimate the maximum measurable velocity to be around 0.59 m/s if the Smart Camera would be positioned at around 24.6 centimeters from the ground.

**Comment by vashmata** [comment]
This ROS package may help but as you said it looks a bit old: https://github.com/cvg/px-ros-pkg

**Comment by vashmata** [comment]
Measured the lens we have and its diameter looks like 8mm and not 16mm but the best way to know would be to move it around and see what the max speed we measure from it is

**Comment by MartensCedric** [comment]
Further testing showed that this device is not meant to be used for a rover. The velocity that the device gives is way too off for our needs. Another device must be found

**Comment by MartensCedric** [comment]
Closed because smart camera was shit
