### ISSUE TITLE
Simultaneous camera streams backend

### ISSUE THREAD

**Issue by PeterGhimself** [space-concordia-robotics/robotics-prototype#151]
Currently the way video streaming is implemented in the code base is that by design we restrict the odroid to only dispatching one stream at a time, so always the same link is used on the client to capture this stream. In fact the current placement of usb cameras does not allow us to stream multiple at the same time, since they are all connected to the same USB hub connected to a single port, there isn't enough bandwidth to stream two over said port, but there may be if we reorganize the usb camera placements with one on the 2.0 hub and another on the 3.0 hub. The default resolution we stream at is 720p (SD). This issue would deal with modifying the backend to allow multiple streams to be on at the same time.
We know that with our ERC radios we get a bandwidth of ~90 Mbps (source: @Waleed-HM ) so it should be able to handle the amount of data being streamed over the rover network. If any issues arise due to this the streaming individual cameras at lower resolution could help mitigate those issues.

- [x] Backend
- - [x] Update task handler and `start_ros_stream.sh` to be able to handle multiple streams at once
- - [x] Dynamic comp/local test mode configuration
- - [x] Test if streaming at lower resolutions allows for multiple streams active on odroid at the same time
- - - [x] 240p --> allows 3 streams max
- - - [x] 360p --> allows 2 streams max, when starting 3rd one we get: `VIDIOC_STREAMON: No space left on device` and the [blue light flicker](https://obsproject.com/forum/threads/logitech-webcam-c920-flickering.95956/)
- - - [x] ~~480p~~ --> allows 1 stream max
- - - [x] ~~720p~~ --> turning on second camera makes the blue light flicker
- - [x] Modify rover usb port configuration for cameras to be able to stream more than one camera
- - [x] Add sub command in task handler for camera stream, new option to get available video usb ports
- - [x] Add support for checking which camera stream ports are currently active
- [x] Address breaking changes to frontend
- - [x] Temporary fix for incorrect URL on frontend, not to enter the scope of #201
- [x] Regression test on rover
- [ ] Optional
- - [ ] Include setting default resolution in `cv_camera` node instantiation
- - [ ] Add feature for request to start/restart node with specific resolution
- - [ ] Front end for start/restart node with specific resolution (dropdown list of reasonable options)
- - [ ] Add response for request which ports are available

**Comment by MartensCedric** [comment]
From my convo with @PeterGhimself 

> Another thing that I think is a bit messy is the placement of the camera rotation.
The problem is that the button is included in "ExtraControls" which is kind of messy considering we have a stream on every page and that the "Streams" page (3 streams" may require 3 of these buttons. So I propose that eventually these stream itself with the button to flip and take a screenshot is 1 template). This can be done in multiple streams issue. I would just comment if you agree

**Comment by KoaTheKoala** [comment]
Just to clarify, you want the following to be bundled into the same html code:
The stream, the button to flip the stream, and a button to take a screenshot?


Koa


-------- Original message --------

**Comment by MartensCedric** [comment]
@KoaTheKoala , yup however it should be neatly placed. (right now those buttons take a lot of space. It should just be a rotate icon and a camera (screenshot) icon .

Cheers

**Comment by KoaTheKoala** [comment]
Sure thing, I can do that.



Sent via the Samsung Galaxy S8+, an AT&T 5G Evolution capable smartphone


-------- Original message --------

**Comment by MartensCedric** [comment]
A few weeks ago we discussed this layout. Just adding it here @KoaTheKoala 
![multiplecamerastreams](https://user-images.githubusercontent.com/18620025/66716380-310a8e80-ed9b-11e9-8a83-525e75fc52c8.png)

**Comment by PeterGhimself** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [A15.3 Multiple Streams Assessment](https://trello.com/c/28T69OPU/158-a153-multiple-streams-assessment)

**Comment by PeterGhimself** [comment]
Alright so after doing some testing by modifying the resolution set in the `start_ros_stream.sh` script responsible for starting up video streams I think the main conclusions to make:
- 3 cameras work with our current setup but only at a measly 240p which looks too small in my opinion
- 2 cameras work with our current setup at 360p, which in my opinion is good enough
- Any resolution higher than that only works with one stream at a time, except 1080p which simply does not work at all

That being said, I propose the following approach moving forward:
I will test if I can simply keep the default at 360p and trade places of one port on the usb hub (so for example the one assigned to "Rear" camera) with one of the teensies usbs (like "Rover" teensy).
I think that's the smallest amount of change necessary then to in theory be able to see all streams at the same time. I'm not testing for multiple basestations viewing it, so I'm not setting out to determine that. Any thoughts @KoaTheKoala ?
I know when it will come time again for ERC we will have a requirement to get a minimum resolution on pictures and for dealing with that I would suggest that we make an issue to give the user an option to start a camera stream with any supported resolution option. Scope of #201 maybe?
Also, I noticed that when the blue light flickering happened the output from the task handler kept spamming: `VIDIOC_STREAMON: No space left on device` after which that same camera would not be able to be turned on again until after rebooting the system. We can either open a new issue to deal with this case or I can perhaps look into it and deal with it here in my PR #248 ,

### 3 cameras at 240p
![3_cameras_240p](https://user-images.githubusercontent.com/19865282/71500705-2a38d700-2834-11ea-9e9c-b23078f8ced6.png)

### 2 cameras at 360p
![2_cameras_360p_part2](https://user-images.githubusercontent.com/19865282/71500732-3d4ba700-2834-11ea-8195-9d814f9419d0.png)

### 1 camera at 480p
![1_camera_480p](https://user-images.githubusercontent.com/19865282/71500745-4472b500-2834-11ea-8ac8-4f95a37118c5.png)

So far we've been doing 720p by default, pretty sure 1080p does not work at all.

**Comment by PeterGhimself** [comment]
Front end account for local mode:
![local_stream_hack](https://user-images.githubusercontent.com/19865282/71560999-91c27280-2a3e-11ea-982f-7e6d495f908d.png)

As well as competition mode (as you can see resizing the frontend to such a small scale causes overlap, decent work around could be solving #258 ):
![goodshit_lol](https://user-images.githubusercontent.com/19865282/71563405-b75e7480-2a5c-11ea-9af5-18592c2a5d10.png)

**Comment by PeterGhimself** [comment]
Front end account for local mode:
![local_stream_hack](https://user-images.githubusercontent.com/19865282/71560999-91c27280-2a3e-11ea-982f-7e6d495f908d.png)

As well as competition mode (as you can see resizing the frontend to such a small scale causes overlap, decent work around could be solving #258 ):
![goodshit_lol](https://user-images.githubusercontent.com/19865282/71563405-b75e7480-2a5c-11ea-9af5-18592c2a5d10.png)

**Comment by PeterGhimself** [comment]
Front end account for local mode:
![local_stream_hack](https://user-images.githubusercontent.com/19865282/71560999-91c27280-2a3e-11ea-982f-7e6d495f908d.png)

As well as competition mode (as you can see resizing the frontend to such a small scale causes overlap, decent work around could be solving #258 ):
![goodshit_lol](https://user-images.githubusercontent.com/19865282/71563405-b75e7480-2a5c-11ea-9af5-18592c2a5d10.png)
