### ISSUE TITLE
Joystick controls revamp

### ISSUE THREAD

**Issue by vashmata** [space-concordia-robotics/robotics-prototype#167]
In #108 we handled the wheels, arm and camera servos.

Next up:
- [ ] Arm control
- - [ ] Implement and test inverse kinematics controls
- [ ] Cameras control
- - [ ] Implement button to take pictures
- - [ ] Implement buttons to switch camera feeds
- [ ] Drill Controls
- [ ] PDS controls?
- [ ] Switch between modules
- - [ ] Switch between everything and drill
- - [ ] Switch between everything and pds

**Comment by MartensCedric** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Joystick Controls Revamp](https://trello.com/c/Mfm394gZ/161-joystick-controls-revamp)

**Comment by Waleed-HM** [comment]
I would like to continue work on this.
