### ISSUE TITLE
Investigate why activating the listener in the GUI causes issues

### ISSUE THREAD

**Issue by MartensCedric** [space-concordia-robotics/robotics-prototype#169]

**Comment by PeterGhimself** [comment]
Suggestion branch name: `bad-gui-169`

**Comment by PeterGhimself** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [A5.1 Analysis/Testing Listener Reliability](https://trello.com/c/hmLXfkqk/138-a51-analysis-testing-listener-reliability)

**Comment by vashmata** [comment]
Please provide a description for this issue
