### ISSUE TITLE
Motor table currents

### ISSUE THREAD

**Issue by PeterGhimself** [space-concordia-robotics/robotics-prototype#17]
Users shall be able to see the current drawn by each motor

- [ ] Arm
- - [ ] Hardware capable of getting currents
- - [ ] Teensy gets current readings per motor
- - [ ] Publish to ros topic
- - [ ] GUI subscribe and display values in table
- [x] Rover
- - [x] Hardware capable of getting currents
- - [x] Teensy gets current readings per motor
- - [x] Publish to ros topic
- - [x] GUI subscribe and display values in table

Currently we need to wait on confirmation for the hardware spec details from @TheRealJeff before moving on with this part

- [ ] Science
- - [ ] Hardware capable of getting currents
- - [ ] Teensy gets current readings per motor
- - [ ] Publish to ros topic
- - [ ] GUI subscribe and display values in table

**Comment by MartensCedric** [comment]
@PeterGhimself Jeff is confused about the science part, should we remove?

**Comment by PeterGhimself** [comment]
For now leave it there but add a note above it. I'll take care of it.
