### ISSUE TITLE
Users shall be able to see the current angle position of each motor

### ISSUE THREAD

**Issue by PeterGhimself** [space-concordia-robotics/robotics-prototype#18]
Use cases:
- 4.1.4 View motor positions
Once the motor positions have been obtained they should populate the motor table so the user can see a visual update as they change

**Comment by vashmata** [comment]
Currently we are capable of visualizing the angles of the arm joints and the velocities of the wheels, so this issue is dealt with.

**Comment by vashmata** [comment]
Closed via #102
