### ISSUE TITLE
Proper Input handling

### ISSUE THREAD

**Issue by MartensCedric** [space-concordia-robotics/robotics-prototype#182]
Currently the input handling is not well designed. In the issue #160, I suggested a centralized approach where we would include `input.js`. The completion of this issue requires to create a file called `input.js` which is able to keep track of the different input states. This file should also have many constants which would be useful. Alternatively, find a library that does it already. The code should entirely be refactored with these new changes

**Comment by MartensCedric** [comment]
- [ ] add listeners
- [ ] clear listeners
- [ ] constants available for all keys we use
- [ ] warn on key used for many purposes (optional)

**Comment by akhilrajkiz** [comment]
```
input.addSimultaneousListener('P', 'CTRL', 'ALT', function(){
  printSomething();
})
```

```
input.add=Listener('P', function(){
  ChangeGUItoRed();
})

```

**Comment by akhilrajkiz** [comment]
//In input

```
function addListener(key, function)
{
num = convertKeyToInt(key)

arrayOfFunctions[num] = function
}

document.addEventListener('keydown', function(event){
num = event.code
executeFunction((arrayOfFunctions[num])
})
```

**Comment by akhilrajkiz** [comment]
https://en.wikipedia.org/wiki/Observer_pattern
