### ISSUE TITLE
Motor statuses

### ISSUE THREAD

**Issue by PeterGhimself** [space-concordia-robotics/robotics-prototype#19]
Users shall be able to see whether a motor is alive or dead, or has errors

- [ ] Write correct logic to indicate that motor is dead, or alive based off current and motion feedback (MCU level detection)
- [ ] Publish said states to topic
- [ ] Subscribe to topic on GUI and display

Use cases:
- 4.1.5 View status of motors
This will provide the user with information about which motors need to be troubleshooted. A `dead` or `alive` label will be obtained based off whether the current draws are in expected ranges during motor movement/idlement, including 0 or unsuspecting max current.
Additionally when the motor status is in safe ranges, the corresponding rows will have a green background; when the motor status is close to the max current values (by a margin of 5%) the corresponding rows will have a yellow background; when the motor status is in the dangerous range - and thus when the status of a motor is `dead` - the corresponding rows will have a red background.
An exception case to `dead` or `alive` state would be `error`, which would be triggered by the current being in moving range, but angles being constant, or the current being in idle range but angles changing (however, this would not apply to finger motor 6). The corresponding row will then have an orange background.

**Comment by vashmata** [comment]
The only way we would be able to guess if a motor is working or not would be through some logical leaps using the current measurements from this issue: https://github.com/space-concordia-robotics/robotics-prototype/issues/17 but it's not ideal.

**Comment by PeterGhimself** [comment]
Hey @vashmata what do you think of this description in the use case? @MartensCedric and I are auditing the issues, I wanna know if you think this is a reasonable approach to getting the statuses of motors in general

**Comment by vashmata** [comment]
I think it's generally ok but we should clarify dead/alive with error. If the motor isn't turning and the current draw is lower than expected then we know it's dead or there's a broken wire. If the motor isn't turning and the current draw is way too high then it's dead or there's a shorted wire. Etc. And cases where the encoder is working or not, cases where the current is in hte expected range but the motor speed isn't matching i

**Comment by PeterGhimself** [comment]
@vashmata good points. I feel like there _may_ even be some unforeseen results that we will only find out during testing
