### ISSUE TITLE
Implement SCP to transfer files from rover to host computer

### ISSUE THREAD

**Issue by MartensCedric** [space-concordia-robotics/robotics-prototype#192]

**Comment by PeterGhimself** [comment]
This is in relation to the epic #113 
I think this should be blocked by the panorama feature actually working first.

**Comment by MartensCedric** [comment]
It is true that it is in relation to epic #113 . It is not required to be blocked as the script is to simply show that you can transfer an image from rover to host. This task can be done in parallel with any other.

**Comment by PeterGhimself** [comment]
On second thought, in theory it should not have to actually depend on that. But I have set #135 as a blocker before work starts here. We should at least have set in stone where panorama snapshots are saved so that mock pictures can be organized properly for testing and working on this issue.

**Comment by MartensCedric** [comment]
@PeterGhimself this makes sense. But let's be honest that #135 is quite trivial. @badgerwild could you also do #135 too?

**Comment by badgerwild** [comment]
@MartensCedric @PeterGhimself I'll take care of #135 .

**Comment by badgerwild** [comment]
Following a discussion with @PeterGhimself , renamed issue to reflect a more general application of the script since it can be used for transferring any file type.
