### ISSUE TITLE
Current selected MUX channel not shown

### ISSUE THREAD

**Issue by PeterGhimself** [space-concordia-robotics/robotics-prototype#196]
Probably through changes in #175 

How to test:
- Run the GUI
- In local mode, simulate mux server: `rosrun mux_selector mux_select_server.py local`

**Comment by MartensCedric** [comment]
Furthermore, I did a complete `git bisect` on the commits where there is a local mode for the mux_selector. I could not reproduce the original intended behavior anywhere. There seem to be a communication problem
