### ISSUE TITLE
Unit tests for the branch verification

### ISSUE THREAD

**Issue by MartensCedric** [space-concordia-robotics/robotics-prototype#199]
There should be unit tests to ensure that the branch verification works. They can also be used for regression testing.

- [x] Port existing bash script to python
- [ ] Implement unit tests

**Comment by NinjaWeeaboo** [comment]
For some reason, I can no longer get python git hooks to work. I even tested a previous commit where it did work. So this will need further testing

**Comment by MartensCedric** [comment]
@NinjaWeeaboo This issue is now resolved with 79ebb3b . 

Script did not have execute permission

**Comment by NinjaWeeaboo** [comment]
@MartensCedric Thanks my dude
