### ISSUE TITLE
Ensure that all stdout are using roslogs

### ISSUE THREAD

**Issue by MartensCedric** [space-concordia-robotics/robotics-prototype#203]
The issue here is that we cannot make full use of ROS log levels if we have not made the use of roslogging consistent throughout the code base. After this is done we can tackle #202 and profit.

**Comment by PeterGhimself** [comment]
In the case that there is no reliable way to use roslibjs for stuff like we see in python `rospy.loginfo()` then perhaps we can simply implement it differently for the JS as a workaround? It must be proven that there is no alternative method.
