### ISSUE TITLE
CLI rover control

### ISSUE THREAD

**Issue by PeterGhimself** [space-concordia-robotics/robotics-prototype#209]
Right now we have two main ways of moving the rover: using keyboard with the GUI or joystick with the GUI. We should have a 3rd way of controlling independant of the GUI which will work on keypress. Implementation for input handling can be based off of [here](https://github.com/space-concordia-robotics/robotics-prototype/blob/master/robot/demos/RemoteRoverControl/ClientSender.py)

The method of sending commands to the rover should be abstracted into a class so that it can be more easily applied to any other code that would depend on being able to move the rover (such as autonomy for autonomous traversal mission).

- [ ] Implement @KoaTheKoala 's requested functions along side with CLI script with it's own event loop to test the commands
- - [x] Go forward or backwards with variable speed
- - [x] Turn left or right with variable speed
- - [x] Full stop
- - [ ] Slow stop
- [ ] Abstract away event loop into class?
- - [ ] Not possible. Instead add new "requests" to the rover listener node which will itself implement the constant stream of budge commands and continously check for connectivity to basestation. As soon as the basestation connection is "severed" the listener will cease any command sending to the rover MCU. (This should be a default for safety reasons).

**Comment by PeterGhimself** [comment]
According to @KoaTheKoala there are 6 things from the autonomys team perspective that we want to have out of this:

- Go forward or backwards with a variable speed
- Turn left or right with variable speed
- Full stop
- Slow stop

To clarify, the stops have nothing to do with PDS i.e cutting power to motors.

**Comment by vashmata** [comment]
> According to @KoaTheKoala there are 4 things from the autonomys team perspective that we want to have out of this:
> 
> * Go forward or backwards with a variable speed
> * Turn left or right with variable speed

What do you think about requesting that the rover drive x metres/degrees or x seconds rather than simply driving until a command is sent to stop driving, @KoaTheKoala ? Has this option been discussed?

**Comment by MartensCedric** [comment]
I would strongly suggest that the interface between the commands and the RoverNode should use Twist command. This would make our rover work in Gazebo. The unified interface would make us avoid copying code for the joystick and the gui. We would have access to abundent ROS related tools by avoiding reinventing the wheel.

**Comment by MartensCedric** [comment]
Please do not implement actual CLI controls when you can just use the package http://wiki.ros.org/teleop_twist_keyboard

**Comment by MartensCedric** [comment]
I suggest we rescope the issue to use twist commands

**Comment by MartensCedric** [comment]
> I suggest we rescope the issue to use twist commands

Actually, no. This issue should be the action server that interfaces between autonomy commands and the RoverNode

**Comment by MartensCedric** [comment]
This is done and works because Twist works with the rover now
