### ISSUE TITLE
Can't build cv_camera on a new setup

### ISSUE THREAD

**Issue by MartensCedric** [space-concordia-robotics/robotics-prototype#220]
Following the current readme will lead to an error while building cv_camera. The fix is to require new users to install some dependencies that contain the .cmake files.

**Comment by MartensCedric** [comment]
@KoaTheKoala , I remember you knew what those commands were. Do you still remember?

**Comment by MartensCedric** [comment]
Apparently, these commands are 
```
sudo apt-get install ros-kinetic-cv-camera
sudo apt-get install ros-kinetic-web-video-server
```

**Comment by MartensCedric** [comment]
Can you check @AFknUsername ?

**Comment by AFknUsername** [comment]
It built succesfully now

**Comment by MartensCedric** [comment]
Ah yes it does build for you @AFknUsername, but we should put the fix in the ReadMe.md (which is what the issue is about). As long as it isn't in the readme, people will be missing packages upon building

**Comment by AFknUsername** [comment]
So, I need to add a section saying to install the dependencies before running cv_camera as a temporary fix?

**Comment by MartensCedric** [comment]
Well the task isn't assigned to anyone. The readme file would be need to be updated with this 

```
sudo apt-get install ros-kinetic-cv-camera
sudo apt-get install ros-kinetic-web-video-server
```
It also needs to contain an explanation on why we need to install this stuff which can only be written by someone familiar with the camera stream components. So there's no action required on your side basically, the reason why you were tagged 25 days ago was to make sure that it fixed your problem, now the next step is updating the readme.

**Comment by AFknUsername** [comment]
Ok, I see. I thought you forgot to close it. Didn't realize there was more to be done, but that makes sense.

**Comment by MartensCedric** [comment]
@AFknUsername Now it is closed (I added the fix) and tbh it was kind of "high priority" because it makes every new member have a disfunctioning setup lol
