### ISSUE TITLE
Investigate NIRScan nano compatibility with Linux

### ISSUE THREAD

**Issue by PeterGhimself** [space-concordia-robotics/robotics-prototype#228]
The only available versions of the GUI are for [Windows/Mac](http://www.ti.com/tool/DLPNIRNANOEVM).

This issue is to look into the feasibility of running the same software in linux, with the ultimate goal of being able to get the csv data and corresponding graphs when running a scan with the NIRscan nano.

**Comment by PeterGhimself** [comment]
Found a relevant [thread](http://e2e.ti.com/support/dlp/f/94/t/688895?tisearch=e2e-sitesearch&keymatch=NIRscan%2520Linux) on the forums, will see if I can run the example code succesfully on Linux from my laptop, then on the odroid.

**Comment by PhilCarPi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [A31.4 Comms](https://trello.com/c/nkCklSDk/98-a314-comms)
