### ISSUE TITLE
Improve voltage and temperature display with icons

### ISSUE THREAD

**Issue by MartensCedric** [space-concordia-robotics/robotics-prototype#229]
Currently the navbar's right side looks like shit.

Voltage icon with current voltage.

Temperature icon with three values.

**Comment by MartensCedric** [comment]
Also when the voltage or temperature goes beyond a critical value, the color of the text should be changed to something that pops

**Comment by adrientremblay** [comment]
below or equal 12.5 V -> modal popup warning to turn robot off and disconnect BMS
over or equal to 16.9 V -> modal popup warning overcharged turn off, go discharge and disconnect BMS

No temperature sensor but valid range is 0-85 degrees

**Comment by vashmata** [comment]
> below or equal 12.5 V -> modal popup warning to turn robot off and disconnect BMS
> over or equal to 16.9 V -> modal popup warning overcharged turn off, go discharge and disconnect BMS
> 
> No temperature sensor but valid range is 0-85 degrees

Keep in mind there should be a way for developers to easily disable this because sometimes the sensors happen to be unplugged or the microcontroller is off or something.

**Comment by PeterGhimself** [comment]
@vashmata I think that just having a feature toggle in the code is enough, but I agree it's a good idea to include in this PR for the reasons you brought up.
