### ISSUE TITLE
Science page URC 2020

### ISSUE THREAD

**Issue by PeterGhimself** [space-concordia-robotics/robotics-prototype#230]
Wireframe:
![new-science-wireframe](https://user-images.githubusercontent.com/19865282/69992832-90258d80-1518-11ea-86d5-4d5a53e9167c.PNG)

Only 8 cuvettes though on the turntable/carousel:
![science_carousel_urc_2020](https://user-images.githubusercontent.com/19865282/69993233-64ef6e00-1519-11ea-9d33-54dfd4f6d2d9.PNG)

**Comment by PeterGhimself** [comment]
I would suggest that we change the route of the old science page from `science` to `science/erc2019` and make the new one `science/urc2020`

**Comment by PhilCarPi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [A31.5 GUI](https://trello.com/c/IDrRJzbN/202-a315-gui)

**Comment by MartensCedric** [comment]
Good wireframe. Although it is a bit incomplete. I'll ask someone else to continue this

**Comment by MartensCedric** [comment]
- There should be no excavate button
- There's no fan speed control
- There is 3 temp sensors
- Currents?

**Comment by PeterGhimself** [comment]
The previous one was done using mockflow.com

If someone wants to work on this let me know and I'll send you my credentials so you can access the previous version. Can speed up time significantly.
