### ISSUE TITLE
Improve the user friendliness of the hotkeys for the claw and arm controls

### ISSUE THREAD

**Issue by MartensCedric** [space-concordia-robotics/robotics-prototype#233]
Keys from claw controls are WERSDF but it is not obvious. The template should be slightly changed to include something that makes it easy for users to know what keys are supposed to be pressed. Either a tooltip, writing the key in the button, next to it, or anything else discussed and agreed in this thread

**Comment by vashmata** [comment]
On a related note, has anyone gone through the different pages and checked to make sure that:
1. for each keyboard-bound key there's an on-screen button, and vice versa?
2. both the keyboard-bound key and the on-screen button result in the desired behaviour?
