### ISSUE TITLE
Closed loop wheel control jitters

### ISSUE THREAD

**Issue by PeterGhimself** [space-concordia-robotics/robotics-prototype#236]
When driving the rover using the current closed wheel control implementation, after driving and then stopping the motors seem to still be drawing current since we can hear them making their typical sounds.
The rover won't be driving away anytime soon from this while being idle in closed loop mode after initial drive commands have been sent, but clearly it is a problem since when no commands are sent the motors should not be drawing any current/trying to move.

- [ ] Investigate cause of jitters
- [ ] Implement fix

**Comment by PeterGhimself** [comment]
I should add that when driving the rover with closed loop control it seems less finer than open loop. What I mean specifically is that using the same "speed" in closed loop moves the wheels faster/more than in open loop which makes it harder to do very small precise movements.

**Comment by vashmata** [comment]
The best way to resolve this issue may simply be to do a review of the rover mcu code and potentially rewrite it.

**Comment by vashmata** [comment]
based on discussions with @fauziame , he will first handle #127 , then create a new issue to adjust PID gains from the GUI, and finally try adjusting the rate at which the PID and the GUI work to find a sweet spot. I'll adjust the issue description.
