### ISSUE TITLE
Rover page closed loop button inconsistency

### ISSUE THREAD

**Issue by PeterGhimself** [space-concordia-robotics/robotics-prototype#237]
## First some context
When starting up the rover page, we will see that buttons like "activate listener" will actually change their states (ON/OFF) based off a query to the rover. So starting up as well as refreshing the page should always properly inform the states of all these relevant state toggle buttons where/when appropriate.

## The problem
Currently the closed loop toggle button falsely indicates on startup of the GUI that the closed loop functionality is OFF on the rover, when in fact it is by default ON.

So as operators to work around this we tend to do the following before before sending drive commands:
1. Enable closed loop mode
2. Disable closed loop mode

On page initialization the button should be set in the appropriate state.

## FYI
The reason open loop mode is currently prefered is due to the related issue #236 

## Task breakdown list
- [ ] Button state of `closed loop` toggle button on rover page is appropriately selected on page initialization
- [ ] (Optional) Ensure that the rover/wheel MCU initiatilizes itself with open loop ON (especially if #236 is still open)

**Comment by vashmata** [comment]
In this specific case it may be more appropriate to use ROS parameters rather than having pub/subs. Also, the ability to track whether motors are in open or closed loop would be useful for the arm page too.
