### ISSUE TITLE
Change terminal command in README for setting up hooks

### ISSUE THREAD

**Issue by AFknUsername** [space-concordia-robotics/robotics-prototype#241]
The second command in the README is `cp branch-verification-hook.sh .git/hooks/post-checkout`
but it should be `cp branch-name-verification.sh .git/hooks/post-checkout`

**Comment by MartensCedric** [comment]
F

**Comment by MartensCedric** [comment]
I think im the retard to `git blame`

**Comment by PeterGhimself** [comment]
via #243
