### ISSUE TITLE
Determine python utility class location(s)

### ISSUE THREAD

**Issue by MartensCedric** [space-concordia-robotics/robotics-prototype#245]
- [ ] Determine the structure of the utility classes 
- [ ] Determine the location
- [ ] Add the utility functions to it and import the class(es) in the original files

**Comment by vashmata** [comment]
Can you explain the purpose of this issue?

**Comment by NinjaWeeaboo** [comment]
@vashmata I assume that this would be to make some of the python code cleaner. Where some functions would be reorganised into several python files, instead of having a ton of functions within a single file. Like what I did for the stream capture issue, where I created the `steam_capture.py` file.

**Comment by vashmata** [comment]
Ok, basically I didn't understand what a utility class is
