### ISSUE TITLE
Branch name verification script blocks ability to use git rebase

### ISSUE THREAD

**Issue by PeterGhimself** [space-concordia-robotics/robotics-prototype#247]
## Problem description

I was trying to edit the commit message of `HEAD^`  using `git rebase -i HEAD~1`, and when I tried I got the following output because of the [branch name verification hook](https://github.com/space-concordia-robotics/robotics-prototype/blob/master/commit-message-hook.sh):

```
(venv) beep@boop:~/Programming/robotics-prototype$ git rebase -i HEAD~2
Note: checking out 'd68fac48cf4bed1d314d946f2737c22673f8a4a8'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at d68fac4... [#151] Static local mode config
fatal: ref HEAD is not a symbolic ref
Branch name is not named properly, please see wiki for formating: https://github.com/space-concordia-robotics/robotics-prototype/wiki/Git-Workflow-and-Conventions
could not detach HEAD
```

After disabling it I was still blocked by the [commit message hook](https://github.com/space-concordia-robotics/robotics-prototype/blob/master/commit-message-hook.sh), as you can see by the following output:

```
(venv) beep@boop:~/Programming/robotics-prototype$ git rebase -i HEAD~2
[detached HEAD dc6ac4a] [#151][#244] Task handler portion allows simultaneous streams
 Date: Wed Dec 18 16:43:58 2019 -0500
 1 file changed, 57 insertions(+), 27 deletions(-)
fatal: ref HEAD is not a symbolic ref
Branch name is not named properly, please see wiki for formating: https://github.com/space-concordia-robotics/robotics-prototype/wiki/Work-Flow
Could not apply cbcd8f246dd1017a95d90b58682151e38c13b5eb... [#151][#244] Update Listener class, start_ros_stream script and task handler to allow simultaneous camera streams
```

When rebasing you end up checking out a new branch which gets named in the format `(no branch, rebasing simultaneous-streams-151)` for example, so this branch name pattern should allowed. And the commit message hook also checks the branch name aswell (which arguably it shouldn't).

## Task breakdown
- [ ] Fix branch name verification hook
- [ ] Fix commit message hook

**Comment by PeterGhimself** [comment]
For now the workaround is to temporarily disable the hook

**Comment by MartensCedric** [comment]
also fails to work with vim-fugitive

**Comment by MartensCedric** [comment]
same reason I believe
