### ISSUE TITLE
Left rear wheel stuck in forward direction

### ISSUE THREAD

**Issue by PeterGhimself** [space-concordia-robotics/robotics-prototype#250]
Unclear if this is simply a hardware or only software issue at the moment, but through testing it has been found that the left rear wheel only moves forward when sending any steering or throttle drive commands. It doesn't move unless told to, though.

**Comment by vashmata** [comment]
May be related to #173

**Comment by MartensCedric** [comment]
This appears to be a wiring issues. Doesn't occur in master with the new rover @PeterGhimself
