### ISSUE TITLE
PDS provide/cut power to ALL motors buttons do not work

### ISSUE THREAD

**Issue by PeterGhimself** [space-concordia-robotics/robotics-prototype#252]
While the individual motor commands work, the cut and provide power to ALL motors buttons do not work. This can be tested on a higher level by trying to move motors with the rover page after trying to cut power to all motors.

Here is the output in the console when pressing the "cut power" and then the "provide power" to all motors buttons:

![ting_robo](https://user-images.githubusercontent.com/19865282/71430349-3e949c80-2699-11ea-8ca2-69a4d44d6980.png)

**Comment by NinjaWeeaboo** [comment]
Fixed this in [#140]. Will close issue after the PR is merged.
