### ISSUE TITLE
GPS Canvas

### ISSUE THREAD

**Issue by MartensCedric** [space-concordia-robotics/robotics-prototype#257]
A canvas should be present to see the rover and it's objective. In this issue, these should be present 

- [ ] The rover should be an arrow/symbol which we can see its direction
- [ ] Goals should be present

**Comment by vashmata** [comment]
I did some very basic work on this which may or may not have been removed from the current GUI code. I made a few dots appear on top of the placeholder map and I stuck them at different locations. Eventually the idea was for the dots to update based on the GPS and direction data coming in through roslibjs. Could be totally useless but worth pointing it out.

**Comment by MartensCedric** [comment]
Closing as duplicate of #56
