### ISSUE TITLE
Unhandled exception when OBC usb hub root bandwidth exceeded by camera stream request

### ISSUE THREAD

**Issue by PeterGhimself** [space-concordia-robotics/robotics-prototype#261]
If a camera_stream is requested that will require more bandwidth than our OBC can support we will get a false positive success message aknowledgment from the task handler and that port will not be usable until we restart the odroid. The task handler process will spit out the error message: `VIDIOC_STREAMON: No space left on device` when this happens.

This issue should handle that exception and investigate on the best method to recover from the broken port after the fact. It is known that a system reboot would fix it, but that is very costly timewise and perhaps there is a better way like by somehow re-intializing the port alias mapping done [here](https://github.com/space-concordia-robotics/robotics-prototype/blob/master/robot/rover/config/my-webcams.rules).

**Comment by vashmata** [comment]
Is this something that would only affect the Odroid? If not, maybe you can slightly expand the scope to also keep in mind whatever limitations the new OBC has.
