### ISSUE TITLE
Test ar_track_alvar ROS package

### ISSUE THREAD

**Issue by KoaTheKoala** [space-concordia-robotics/robotics-prototype#262]
This package should provide an easy way to automatically detect AR tags without having to create a package from scratch. If it does work, we need to know what the limitations of the package are to see if it is robust enough to use at competition. As such we need to test the following key parameters:

1.  Distance
2.  Angle of rotation (if you're looking at the paper straight on it's 0 degrees)
3.  Lighting

Steps to launch:
`$ roslaunch gscam v4l.launch`
`$ roslaunch webcam_ar_track  webcam_indiv.launch`
`$ rostopic echo -c /ar_pose_marker`
    ^is used to display the ar tag detection info

you can also visualize it in rviz and then adding the Marker and tf

Link to the ros package:
- ar_track_alvar (http://wiki.ros.org/ar_track_alvar)
    used for ar tag detection
 - gscam (http://wiki.ros.org/gscam)
    gscam is a strong altenative to cv_camera, it seems like its simpler, therefore im leaving cv_camera for further testing because it might contain more functionality that we might need in the long run
 - image_pipeline (http://wiki.ros.org/image_pipeline?distro=melodic)
    used for image calibration, no use for now, but we'll have to look into that before deploying it to astro
 - webcam_ar_track
    is a custom script to launch the cam stream with ar_track_alvar

**Requirements:**
- [x] Install ar_track_alvar ROS package
- [x] Print 5-10 AR tags (you may need to use the ar_track_alvar package or something similar to
- [x] Test ar_track_alvar ROS package
- [x] Test distances (these distances can be approximate, we just need a rough idea)
- - [x] Test 1 m
- - [ ] Test 3 m
- - [ ] Test 5 m
- - [ ] Test 10 m
- - [ ] Test 15 m
- [x] Test angles (these angles can be approximate, we just need a rough idea)
- - [x] Test 0 degrees (straight on)
- - [ ] Test 15 degrees
- - [ ] Test 30 degrees
- - [ ] Test 45 degrees
- - [ ] Test 60 degrees
- - [ ] Test 75 degrees
- [x] Test lighting (we will have to come up with a plan to test this)
- - [x] Ambient light
- - [x] Neon light
- - [x] Dim light
- - [ ] Dark room
- - [ ] Full dark
- [ ] Create calibration script for camera
- - [ ] Look into this: http://wiki.ros.org/camera_calibration

**Comment by vashmata** [comment]
URC reminders:
1) Every single post at URC will have its own AR tag, so we'll be able to know which exact post we're looking at based on the AR tag. See 5.Q in the [URC Q&A](http://urc.marssociety.org/home/q-a)
2) According to the URC rules, the posts will have AR tags in the form of a triangular prism constructed of 3 identical AR tags. This means that it's likely for the camera to see the AR tag on two faces of the prism simultaneously. We should test this scenario as well.

**Comment by MartensCedric** [comment]
is this investigated? @KoaTheKoala

**Comment by MartensCedric** [comment]
Can we close this @KoaTheKoala @domludera  I'm gonna open a new issue to transfer ERC code

**Comment by KoaTheKoala** [comment]
@MartensCedric I think it is safe to close this issue, but imo, we should still at least test under different lighting and distance conditions.
