### ISSUE TITLE
Error on initial pip install for venv

### ISSUE THREAD

**Issue by gabrielkarras** [space-concordia-robotics/robotics-prototype#268]
After running this part of the setup instructions (with venv activated):

`pip install -r requirements.txt -r requirements-dev.txt`

I got the following output:

---

[...]

Created wheel for wrapt: filename=wrapt-1.11.2-cp36-none-any.whl size=19590 sha256=6e095034449ef3ce6f8565da191c93945d3e0d3c78451e197adb6bd62ae9e17e
Stored in directory: /home/gabrielkarras/.cache/pip/wheels/d7/de/2e/efa132238792efb6459a96e85916ef8597fcb3d2ae51590dfd

Successfully built empy flask-bootstrap pyyaml tornado bson visitor wrapt

**ERROR: astroid 2.3.3 has requirement six~=1.12, but you'll have six 1.11.0 which is incompatible.**

Installing collected packages: atomicwrites, attrs, six, cycler, empy, kiwisolver, numpy, python-dateutil, pytz, pyparsing, matplotlib, more-itertools, pluggy, py, pyserial, click, itsdangerous, MarkupSafe, Jinja2, Werkzeug, flask, dominate, visitor, flask-bootstrap, pyyaml, docutils, catkin-pkg, rospkg, netifaces, tornado, bson, pymongo, sqlparse, asgiref, django, pillow, image, zope.interface, constantly, Automat, PyHamcrest, idna, hyperlink, incremental, Twisted, pytest, isort, lazy-object-proxy, wrapt, typed-ast, astroid, mccabe, pylint, yapf
Successfully installed Automat-0.8.0 Jinja2-2.10.3 MarkupSafe-1.1.1 PyHamcrest-1.9.0 Twisted-19.7.0 Werkzeug-0.16.0 asgiref-3.2.3 astroid-2.3.3 atomicwrites-1.1.5 attrs-18.1.0 bson-0.5.8 catkin-pkg-0.4.15 click-6.7 constantly-15.1.0 cycler-0.10.0 django-3.0.2 docutils-0.15.2 dominate-2.4.0 empy-3.3.2 flask-1.0.2 flask-bootstrap-3.3.7.1 hyperlink-19.0.0 idna-2.8 image-1.5.27 incremental-17.5.0 isort-4.3.21 itsdangerous-1.1.0 kiwisolver-1.0.1 lazy-object-proxy-1.4.3 matplotlib-2.2.2 mccabe-0.6.1 more-itertools-4.2.0 netifaces-0.10.9 numpy-1.14.5 pillow-7.0.0 pluggy-0.6.0 py-1.5.4 pylint-2.0.1 pymongo-3.8.0 pyparsing-2.2.0 pyserial-3.4 pytest-3.6.3 python-dateutil-2.7.3 pytz-2018.5 pyyaml-4.2b1 rospkg-1.1.7 six-1.11.0 sqlparse-0.3.0 tornado-6.0.2 typed-ast-1.4.0 visitor-0.1.3 wrapt-1.11.2 yapf-0.22.0 zope.interface-4.7.1

---

**Comment by MartensCedric** [comment]
fixed in #412
