### ISSUE TITLE
Users shall be able to switch between manual and automatic controls

### ISSUE THREAD

**Issue by PeterGhimself** [space-concordia-robotics/robotics-prototype#27]
Use cases:
- 4.1.8 Switch controls to manual
A mode of the controls in which the buttons allow the user to move each of the 6 motors respectively in either clockwise or counterclockwise direction.
- 4.1.9 Switch controls to automatic
A mode of the controls in which the buttons allow the user to move the motors automatically in any direction using inverse kinematics.

**Comment by MartensCedric** [comment]
@PeterGhimself I am working on issue #127, where I do have to toggle the `steering` value. I added a button that toggles it. Is this what is referred in this issue? Are these the same things?

**Comment by PeterGhimself** [comment]
@MartensCedric Initially this only referred to arm control, at the time we did not envision the need to do the same for the wheel controls. So yes I would say it is related to this issue, although this issue is really more like an epic (since it refers to both arm and wheel controls now).

**Comment by PeterGhimself** [comment]
Closing this issue as it should be a sub task of the IK task in #132
