### ISSUE TITLE
Obtain Point Cloud & IMU Data from the LiDAR

### ISSUE THREAD

**Issue by KoaTheKoala** [space-concordia-robotics/robotics-prototype#279]
In order to move between two AR tag posts and avoid obstacles, we need to figure out how to process the data received from the Ouster OS1-16 3D LiDAR.

Link for the OS1 spec sheet (towards the bottom of the page):
https://ouster.com/products/os1-lidar-sensor/

Ouster Studio link:
https://ouster.com/get-started/

- [x] Setup LiDAR on PC with the Ouster software
- [x] Receive LiDAR data
- [x] Figure out the format of the LiDAR data and how to receive the data
- [x] Document how to receive data & the format of the data [here](https://docs.google.com/document/d/13Yz4rR6BTb6egGZ9ver90Zd_LEvbzZgipR2qRectWn4/edit#heading=h.qa0s5ofhd1cg)

**Comment by Mina-Magdy** [comment]
The LiDAR has been set up and working properly.
IMU data is being published through the "/os1_cloud_node/imu" topic.
Point Cloud data is being published through the "/os1_cloud_node/points" topic.
For full details, please visit this [link](https://docs.google.com/document/d/13Yz4rR6BTb6egGZ9ver90Zd_LEvbzZgipR2qRectWn4/edit#heading=h.qa0s5ofhd1cg)

**Comment by KoaTheKoala** [comment]
Closed to make more relevant and up-to-date issues.
