### ISSUE TITLE
Local PDS Simulator

### ISSUE THREAD

**Issue by adrientremblay** [space-concordia-robotics/robotics-prototype#284]
This will probably be accomplished by creating a bunch of rospy python scripts.
We need to have some "fake" publishers to mock the real data that would be published if the rover actually on.

launch parameters : mode ...

- [x] Write initial publisher rospy script(s)
- - [ ] Temperature
- - - [ ] Stable
- - - [ ] Unstable
- - - - [ ] start stable and go past max
- - - - [ ] start stable and go past min
- - [x] Voltage

**Comment by MartensCedric** [comment]
I would suggest that we expand this to be a PDS mocker. Thoughts @PeterGhimself ?

I don't think it would be a good practice to have a script per UI element. I think we can make a mock per system though

**Comment by MartensCedric** [comment]
And this issue would basically be a subtask of that Epic @PeterGhimself

**Comment by adrientremblay** [comment]
yeah we definitely need an epic for this

**Comment by adrientremblay** [comment]
Publisher name: PDS-Mock publisher

**Comment by adrientremblay** [comment]
command to set the voltage mock mode` rosparam set /PDS_mock_mode_voltage <mode>`
where <mode> is the mode (stable, rise, fall) for now

**Comment by MartensCedric** [comment]
After my discussion with @ginywiny, here's what we think that the system should do

A high level class/interface should be able to control a float value in three ways.

Either keep it constant, make it rise at a certain rate or make it fall at a certain rate.

In all cases, published values should have noise +- a certain value.

The local_rover.launch files should launch the python node of the pds_local_publisher
The values should all be from rosparameters, written in the local_rover.launch file from <param></param>

The parameters should be the constant value for the constant mode. The noise. The start and rise/fall values for the climbing/falling falling mode.

The system should allow you to control multiple values.
Ex : Voltage Constant, Temperatures increasing, Currents constant.

Voltage should be published to /battery_voltage
Temperatures should be published to /battery_temps (There's 3 temperatures)
