### ISSUE TITLE
View any messages related to any arm subsystems as they are caught

### ISSUE THREAD

**Issue by PeterGhimself** [space-concordia-robotics/robotics-prototype#29]
Use cases:
- 4.1.17 View arm logs
Messages related to subsystems of the arm will be displayed as they are caught and displayed to the user through an error log console.

**Comment by vashmata** [comment]
This happens when ROS and the rest of the comms are functioning correctly.

**Comment by vashmata** [comment]
Closed via #102

**Comment by vashmata** [comment]
Reopened because the log does not display errors from the ROS node. The most obvious errors are when the node does not open because it cannot find the (correct) module (of which there are a few different types of message).

**Comment by MartensCedric** [comment]
Closed because of the discussion me @PeterGhimself and @vashmata had. It will be covered via other issues
