### ISSUE TITLE
Activity Indicator manual control Backend + Firmware

### ISSUE THREAD

**Issue by PeterGhimself** [space-concordia-robotics/robotics-prototype#292]
Autonomy for URC 2020 needs an activity indicator. We also need to show it off for our SAR video.
We must have at least manual control over it and integrated into our system.

Requirements:
- [x] Backend must be updated to support new request to rover MCU
- [ ] Firmware of rover MCU must be updated to accept requests to turn activity indicator light ON/OFF and change colours

**Comment by PeterGhimself** [comment]
I will update the RoverCommandListener to accept the new request, whoever ends up working on the MCU side should make sure to look at my commit first to know what messages to use to recognise the commands, assuming someone else ends up taking up that portion of this task.

**Comment by PeterGhimself** [comment]
Starting development on branch [activity-indicator-control-292](/space-concordia-robotics/robotics-prototype/tree/activity-indicator-control-292)

**Comment by vashmata** [comment]
Just a note that this is related to #112
