### ISSUE TITLE
Investigate issues with custom ROS messages in the GUI

### ISSUE THREAD

**Issue by MartensCedric** [space-concordia-robotics/robotics-prototype#297]
Investigate and resolve the unreliability of the custom ROS message types in the GUI. Resolving this issue resolves #128 

Make sure you check this : https://github.com/RobotWebTools/roslibjs/issues/254

And once the issue is resolved, these message types should be used throughout the codebase : https://github.com/space-concordia-robotics/robotics-prototype/tree/master/robot/rospackages/src/mcu_control/msg

- [x] Restore custom messages
- [x] Pull and catkin_make on rover, have a successful test
- [x] Restore hidden navigation panels to the GUI
- [x] Add [wiki guide](https://github.com/space-concordia-robotics/robotics-prototype/wiki/Robot-Web-Tools-and-ROSlibjs#custom-message-types) to integrating new custom messages/etc to GUI
- [ ] Add guide to running navigation stuff somewhere
- [x] Add flags to custom message types and propagate thru to the front end for N/A cases

**Comment by MartensCedric** [comment]
So I got it working @vashmata

**Comment by MartensCedric** [comment]
@AFknUsername I'm seeing now that Josh did some work

**Comment by vashmata** [comment]
A requirement for closing this issue is that it's tested on the Odroid with me present

**Comment by vashmata** [comment]
I've tested things out on the odroid, it should be ok. @MartensCedric what would be a smart place to put instructions for running the navigation and antenna node? In our comms setup guides I guess? Should I put it in a readme somewhere?
