### ISSUE TITLE
Users shall be able to review arm related logs in a file stored on the base-station

### ISSUE THREAD

**Issue by PeterGhimself** [space-concordia-robotics/robotics-prototype#30]
Use cases:
- 4.1.18 Store arm logs
In order to be able to later review errors seen in the error log panel, the GUI should continuously append any errors from any subsystems to a file so that they can be reviewed after the application has stopped running and while it is running.

**Comment by PeterGhimself** [comment]
csv format

**Comment by MartensCedric** [comment]
Closed as it will be covered via other issues as discussed with @PeterGhimself  and @vashmata
