### ISSUE TITLE
Update git hooks section in README

### ISSUE THREAD

**Issue by AFknUsername** [space-concordia-robotics/robotics-prototype#300]
The section still uses the old way of committing (using `-m`). 
Should be updated to use whatever @PeterGhimself sent in the slack channel a few weeks back.

- [ ] update readme

**Comment by PeterGhimself** [comment]
This is very vague. I just took a look at the README on master and it looks fine. What is the actual specific issue you are trying to define here?

**Comment by PeterGhimself** [comment]
Ok, it's not _super_ vague but can you be more specific? Point is I don't see anything wrong with what is currently there

**Comment by AFknUsername** [comment]
Essentially you told us to just use `git commit` instead of `git commit -m`, there might've been more but the messages on slack get deleted so I can't see

**Comment by PeterGhimself** [comment]
Can you please try to find the exact message because I don't remember this?
If anything I said to do that when doing merge commits, but not in general.
