### ISSUE TITLE
Show N/A as temperature when they temperature is not available instead of 999 degrees

### ISSUE THREAD

**Issue by MartensCedric** [space-concordia-robotics/robotics-prototype#317]
Putting 999 degrees triggers an alert every time we open the page. 

The text written should be N/A and the alert should not pop up

**Comment by vashmata** [comment]
we might wanna change this in the mcu code as well

**Comment by AFknUsername** [comment]
Cannot test without rover as using rostopic pub doesn't go through pdsnode.py
