### ISSUE TITLE
Investigate why camera streams don't work on my machine

### ISSUE THREAD

**Issue by vashmata** [space-concordia-robotics/robotics-prototype#318]
Could be PEBKAC, could be a missing required package.

**Comment by MartensCedric** [comment]
Removed devops tag. I have a feeling its with your setup so idk if this issue is really relevant. But we will keep it open in case its a bug with the code.

**Comment by PeterGhimself** [comment]
Someone needs to try to reproduce this bug. I have been testing with the rover over the last few weeks and have not encountered this issue.
