### ISSUE TITLE
Connection Test

### ISSUE THREAD

**Issue by PeterGhimself** [space-concordia-robotics/robotics-prototype#32]
There is some instructions for testing connectivity in linux between two boxes in [this](https://docs.google.com/document/d/1sXmyh_h9N3C7mqa19TOzDe9GOyu47MAE7F8FrYocC7U/edit#heading=h.wwzri195f18p), worth reading some time ;)

**Comment by MartensCedric** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [A5.2 Connection Test](https://trello.com/c/74FHBccZ/139-a52-connection-test)
