### ISSUE TITLE
ArmNode needs to be started before RoverNode via odroid SSH

### ISSUE THREAD

**Issue by vashmata** [space-concordia-robotics/robotics-prototype#329]
I've noticed that trying to run ArmNode (while RoverNode is running) over SSH tends to fail if I ran RoverNode over SSH first. The reverse order works though.

I don't remember this happening in the past and the way I wrote these nodes was supposed to be such that this shouldn't ever be an issue. That said, we're aware that the serial parsing functions used in these nodes have some inconsistencies, see #324

**Comment by PeterGhimself** [comment]
I think someone should definitely try to reproduce this issue. I have two teensies so I'll volunteer.
