### ISSUE TITLE
Integrate the new IMU code to wheels teensy code

### ISSUE THREAD

**Issue by Waleed-HM** [space-concordia-robotics/robotics-prototype#334]
The SparkFun IMU board has its own ARM based micro-controller. It contains a default code that grabs the data from the IMU chip itself (on the same board) and outputs it on a serial port. We need to:
- [ ] add a block of code on the wheels teensy to receive the IMU information (roll, pitch, yaw, heading) from the IMU board and print it over USB to the OBC
- [ ] possibly send certain commands (the default code on that board can receive certain characters on the serial that enable or disable certain types of information).

**Comment by KoaTheKoala** [comment]
We no longer need the SparkFun IMU since we the purchased the LiDAR and the ZED 2 camera.
