### ISSUE TITLE
Users shall be able to turn on the arm's motors and enable controls

### ISSUE THREAD

**Issue by PeterGhimself** [space-concordia-robotics/robotics-prototype#34]
Use cases:
- 4.1.21 Startup motors/enable controls
By pressing the “enable controls” button the base station shall send a command to the rover that will turn on power to the arm motors via an arduino pin controlled relay switch and enable the PID controller to execute its usual loop.

**Comment by PeterGhimself** [comment]
should be worked at at same time as #33

**Comment by vashmata** [comment]
Issue is not quite relevant anymore since there is no way to enable or cut power to the arm motors

**Comment by PeterGhimself** [comment]
I'm gonna close this via #33 , which I updated the contents of so please review @vashmata
