### ISSUE TITLE
Emphasize the warning when voltage or temperature become in a warned range

### ISSUE THREAD

**Issue by MartensCedric** [space-concordia-robotics/robotics-prototype#342]
Currently, in the GUI, when the battery voltage or the PDS temperatures are in a dangerous range, the operator gets a model popup. However, when the values are close to the danger value, it is in a warning threshold. Other than changing the text to yellow, not much is done. This issue would require the assignee to make it more clear to the operator that it's in the warning threshold. This could be done by changing the background of some component in the navbar. Alternative solutions are also welcome.

**Comment by AFknUsername** [comment]
Alternative solution: Make a huge rainbow arrow fade in and out pointing at the temp value

**Comment by MartensCedric** [comment]
We found a library called notify.js
