### ISSUE TITLE
refactoring before sprint 1

### ISSUE THREAD

**Issue by PeterGhimself** [space-concordia-robotics/robotics-prototype#35]
refer to UML diagrams in [Software Architecture Document](https://docs.google.com/document/d/1QEaR5sP7aWUMgJukAuCMeTT6QKM80vOXxO7XymeWWns/edit)

**Comment by PeterGhimself** [comment]
development started on branch [refactoring-35](/space-concordia-robotics/robotics-prototype/tree/refactoring-35)

**Comment by bnduwi** [comment]
Just added skeletons for the ClientConnecton.py and LoggerBuffer.py classes. Right now they just have the basic layout from the UML in SoAD but will definitely need to be worked to make functional.

**Comment by bnduwi** [comment]
Also just moved this issue from backlog to in progress in ZenHub. One more thing, I think that we need to restructure of files structure to put things that relate to base stattion in one folder and those that relate to rover in another.

**Comment by PeterGhimself** [comment]
@bnduwi I agree.
