### ISSUE TITLE
Look into automated testing of ROS nodes

### ISSUE THREAD

**Issue by MartensCedric** [space-concordia-robotics/robotics-prototype#355]
There are some packages available such as

 http://wiki.ros.org/rosunit
and http://wiki.ros.org/rostest/Writing

These may be useful in testing if a node behaves properly. Some nodes may be easy to test, notably nodes that have easy I/O such as GoalNode and PDS_mock_publisher

**Comment by NinjaWeeaboo** [comment]
Hmm, this will be good for changing over to melodic

**Comment by vashmata** [comment]
Just found this one too http://wiki.ros.org/action/show/Quality/Tutorials/UnitTesting?action=show&redirect=UnitTesting
