### ISSUE TITLE
Error in setup script

### ISSUE THREAD

**Issue by AFknUsername** [space-concordia-robotics/robotics-prototype#359]
### Overview
The script downloaded from https://raw.githubusercontent.com/ROBOTIS-GIT/robotis_tools/master/install_ros_kinetic.sh
adds two lines to the bashrc that break some ROS functionality because it relies on a default 
catkin workspace setup.

The lines in question are:
```
source /opt/ros/kinetic/setup.bash
source ~/catkin_ws/devel/setup.bash
```
We source our own `setup.bash` files, but the conflict remains and it causes errors.

### To recreate the error:
1. make sure you have the lines in your `.bashrc`
2. switch to `localization-map-56` branch
3. run gui and open rover page
4. open console and notice the errors related to `rover_position`

### To fix:
Remove the lines mentioned above from your `.bashrc` and retest.
1. restart your terminal to source the `.bashrc` or use `sb` if you have the alias.
2. restart the gui and verify that the error is gone. 

### More steps
Make sure new members know about this error and fix it manually until a solution has been found

**Comment by AFknUsername** [comment]
The easiest fix I think is to keep a local copy of the install script for ROS and modify it to not include the lines, and maybe edit other things too if necessary.

**Comment by MartensCedric** [comment]
> The easiest fix I think is to keep a local copy of the install script for ROS and modify it to not include the lines, and maybe edit other things too if necessary.

Seems like the correct solution to me.

**Comment by AFknUsername** [comment]
@MartensCedric this needs to be tested, but I'm pretty sure it should work.
