### ISSUE TITLE
ROS arm mirror representation

### ISSUE THREAD

**Issue by PeterGhimself** [space-concordia-robotics/robotics-prototype#36]
Create a ROS simulation model of our arm
Could help to look into possibly transforming solidworks CADs into ROS models, since we already have the arm cadded out in solidworks
The main benefit we hope to achieve with this model is an accurate test bed for inverse kinematics logic (inverse kinematics implementation not part of this task)

Planned steps to achieve this according to Gantt chart:

- [x] Embed a ROS dummy arm mirror into Flask
- [x] Replace the dummy arm mirror with an actual one
- [ ] Make arm mirror self update
- [ ] Integrate ROS support

**Comment by bnduwi** [comment]
![arm_assembly_sim](https://user-images.githubusercontent.com/32171245/49549295-547cc700-f8b6-11e8-83e8-c69303fb3ff3.png)


Steps to reproduce:
- Follow this tutorial on generating a ROS package with URDF from SolidWorks:
-- To install solidworks addin (plugin): http://wiki.ros.org/sw_urdf_exporter
-- To create ROS package for a SolidWorks assembly: http://wiki.ros.org/sw_urdf_exporter/Tutorials/Export%20an%20Assembly (Have to define the joints to add the URDF file)
-- Export the assembly to generate the ROS package. (Name it in lower cases letters with underscores as spaces)
-- To run simulation in Gazebo copy the ROS package in ROS workspace `~/catkin_ws/src`
-- Next build the package by first `cd ~/catkin_ws` and the running `catkin_make` command
-- Running the simulation is supposed to be done in one command but there is an issue so follow these steps:
--- cd into catkin_ws folder and then run `roslaunch <package name> gazebo.launch` (This command will present some errors but the model of the arm has been generated and spawned.
--- To view the model simulation open a separate terminal window and run `roslaunch gazebo_ros empty_world.launch`

**Comment by PeterGhimself** [comment]
Closing via #134
