### ISSUE TITLE
Syntax error on PDS page

### ISSUE THREAD

**Issue by NinjaWeeaboo** [space-concordia-robotics/robotics-prototype#375]
There's a syntax error that prints in the console on the PDS page.
![image](https://user-images.githubusercontent.com/55707515/83212777-6eefd380-a12e-11ea-865b-b4467d2ea698.png)

**Comment by MartensCedric** [comment]
Isn't this the bug you fixed in your command input branch?

**Comment by NinjaWeeaboo** [comment]
oh shit it prob is, MB. My command input branch got messed up from merging master into it
