### ISSUE TITLE
Remove useless C++ files

### ISSUE THREAD

**Issue by MartensCedric** [space-concordia-robotics/robotics-prototype#377]
We have files like "ideas.h" and "notes.h". There's folders with example code which we will clearly never use. Looking through this document might be useful : https://docs.google.com/document/d/1MZaEAh4fQXDNMqdmfaYagB0u23k_reNE0J9pfIDxf2A/edit#

The assignee must remove as much useless files, projects and example projects as he can in the C++ code.

**Comment by MartensCedric** [comment]
@steamypotato for you to :eye: :lips: :eye:

**Comment by vashmata** [comment]
wow stop calling me out

**Comment by vashmata** [comment]
Your issue description makes no mention of the fact that whoever takes this issue upon themselves had better check before deleting anything 🔪 🔪 🔪

**Comment by MartensCedric** [comment]
Fauzi said we can remove demo projects (source the SQA doc and telegram chat with him)

**Comment by vashmata** [comment]
Yeah I'm just making sure it's clear when it comes time to delete my stuff 👀
