### ISSUE TITLE
Science Listener won't turn on in the javascript

### ISSUE THREAD

**Issue by MartensCedric** [space-concordia-robotics/robotics-prototype#397]
1. Open GUI
2. roslaunch the local rover launch in rosRoverStart
3. Go on the science page.
4. Set USB, Science in navbar
5. Toggle the listener -> Will always fail (js error)

This is because there's an inconsitency with the ID

**Comment by PeterGhimself** [comment]
Just to be clear, the actual science listener _does_ run, and this can be confirmed with something like `ps aux | grep ScienceNode`. What fails specifically is the front end toggle button does not appropriately change it's state.
