### ISSUE TITLE
Add a port selection dropdown menu in GUI

### ISSUE THREAD

**Issue by tatumalenko** [space-concordia-robotics/robotics-prototype#41]
# Add a port selection dropdown menu in GUI
Right now we are ~~hardcoding~~ importing the ~~name~~ available ports and using the first one to use when connecting to Arduino with `pyserial`. I already have some Python code to list all available ports open available to connect, just need to incorporate it in a GUI component dropdown menu to allow selection from User.

**Comment by bnduwi** [comment]
Added a drop down for the ports to GUI using glade. Also added a handler to be used when dynamically populating the drop down. The next step is to create a function in the AsimovOperations class and start adding the code for the ports.
