### ISSUE TITLE
Migration to melodic

### ISSUE THREAD

**Issue by AFknUsername** [space-concordia-robotics/robotics-prototype#422]
This issue will keep track of the progress to migrate to melodic.

- [x] venv works
- [x] all pip packages are ok
- [ ] all ros packages are ok
- [x] everything builds on cmake
- [x] update travis-ci to build on bionic
- [x] update submodules

**Comment by RealWilliamWells** [comment]
:eyes: I've been doing all of my dev work on Ubuntu 18:04 and Melodic for ~4 months now, and I have yet to run into any ROS related issues. So for at least running the GUI in local mode, I don't think there should be any issues.

**Comment by AFknUsername** [comment]
@RealWilliamWells 
That's really good to hear! I knew the process would be relatively painless. The only thing I was worried about was the ROS packages potentially breaking.
