### ISSUE TITLE
Display time since laser has been turned on to display that the warmup sequence has been done

### ISSUE THREAD

**Issue by MartensCedric** [space-concordia-robotics/robotics-prototype#444]
Section 3.3 https://docs.google.com/document/d/1N7tWT132qdKljGeyzkHsWxUH83sbp5s3c5rEwCJ0yC4/edit

This should be multiple operator friendly, perhaps the time can be published through the science node. No measurements should be taken prior to the warmup time. Perhaps indicating a warning before taking measurements could be appropriate.

**Comment by Laogeodritt** [comment]
I would suggest that at a business logic level:

* Temperature of the laser is tracked over time, and its stability is assessed (monotonic drift over time, root-mean-square noise if any).
* A threshold of stability for "warmed up" is defined (e.g. no more than 3°C drift over time in the past 30 seconds using a moving window average of 30 seconds - this is just an example, you can figure out what kind of criteria would be enough).

At a GUI level:
* A simple warmed up/still warming up binary indication is shown. 
* Some indication of the temperature-over-time (e.g. current temp, maybe a calculated drift value in K/s, noise values, etc. - whatever is useful) are available to the operator, in case they want to validate the binary indication.
