### ISSUE TITLE
Dispense a specific volume of liquid into a cuvette

### ISSUE THREAD

**Issue by MartensCedric** [space-concordia-robotics/robotics-prototype#446]
This will be based on the results of the tests from the mech team. 

Refer to this document for more information : https://docs.google.com/document/d/1N7tWT132qdKljGeyzkHsWxUH83sbp5s3c5rEwCJ0yC4/edit

The pump is peristaltic pump as shown in this video : https://www.youtube.com/watch?v=pvj4WatP4n4

**Comment by Laogeodritt** [comment]
No flow or volume sensors are available.

Variables to control:

* Motor speed (using PWM)
* Amount of time elapsed

It's likely that beyond a certain motor speed, we'll get more precision by running slower for longer. However, this might not matter even at full speed.

Repeatability will need to be tested once a solution is implemented (i.e. what's the mean and variance of delivered liquid using the chosen method?).
