### ISSUE TITLE
Turn off laser when there's a fault

### ISSUE THREAD

**Issue by MartensCedric** [space-concordia-robotics/robotics-prototype#447]
When the interrupt signal for a fault. It is super important to ensure that the laser turns off.

Section 3.4

https://docs.google.com/document/d/1N7tWT132qdKljGeyzkHsWxUH83sbp5s3c5rEwCJ0yC4/edit

**Comment by Laogeodritt** [comment]
Clarification: when the FAULT signal is asserted, the laser has already automatically been turned off by the fault detection circuitry.

Firmware will need to toggle the laser OFF then ON again to clear the fault bit and attempt to turn the laser on again. (If the fault is still physically present, FAULT will assert again within less than a second—still need to do analysis on the timing—and the laser will turn off again.)
