### ISSUE TITLE
Toggle fans and make sure they are always on when laser is on

### ISSUE THREAD

**Issue by MartensCedric** [space-concordia-robotics/robotics-prototype#448]
Look at the documentation here : https://docs.google.com/document/d/1N7tWT132qdKljGeyzkHsWxUH83sbp5s3c5rEwCJ0yC4/edit#

From Marc's comment

> 2. Fans MUST run if laser is on. Fans need not run if laser is off. Reason is laser isn't designed for continuous use and may overheat without cooling.
> I would propose that (fan on, laser on) be automatic from one operator command "laser on", and (laser off, fan off) be also automatic from one operator command "laser off".
> There's no timing constraint, as long as there's no chance that the laser is on when the fan is off (consider failure modes: what happens if the MCU locks up in between the two actions? this is why I insist on the order).
> There's a possibility this won't matter, but my design is defensive to the idea that we need to cool the laser to be safe and functional. Minor relaxations or changes to the requirement may come at a later time as we test.
> 
>

**Comment by Laogeodritt** [comment]
Depends on #441.
