### ISSUE TITLE
Create Science Software Design Diagrams and skeleton for Teensy 4.0

### ISSUE THREAD

**Issue by MartensCedric** [space-concordia-robotics/robotics-prototype#462]
Prior to start the science project we should have a good understanding of the different components of the system. Some documentation should exist so that the members can implement the code by consulting the documentation. Further, it will be crucial to present these to PDR

Please consult Marc's doc : https://docs.google.com/document/d/1N7tWT132qdKljGeyzkHsWxUH83sbp5s3c5rEwCJ0yC4/edit

Deliverable :

- [x] Class Diagram of Teensy 4.0 planned software
- [x] Physical View
- [x] List of commands sent to command centre (optional for this issue)

Approval
- [ ] @Laogeodritt @vashmata @PeterGhimself At least 2 of these should approve

Once approved, 
- [x] Skeleton code for C++, and PR it

**Comment by MartensCedric** [comment]
![image](https://user-images.githubusercontent.com/18620025/94347959-a7cd8580-0006-11eb-9b6e-a15a7acb6b97.png)

**Comment by MartensCedric** [comment]
@Laogeodritt Does this look accurate to you? Am I missing something important or do I have something wrong? Note that this is for Teensy 4.0 software (Excludes CCD as far as I understand it)

**Comment by MartensCedric** [comment]
@PeterGhimself @vashmata

**Comment by MartensCedric** [comment]
https://docs.google.com/document/d/1N7tWT132qdKljGeyzkHsWxUH83sbp5s3c5rEwCJ0yC4/edit

**Comment by MartensCedric** [comment]
![image](https://user-images.githubusercontent.com/18620025/94348332-262b2700-0009-11eb-8003-7484df8153e2.png)

**Comment by MartensCedric** [comment]
After some thought I think I should also include the list of the commands that the system should accept and their role

**Comment by MartensCedric** [comment]
> After some thought I think I should also include the list of the commands that the system should accept and their role

List of commands : https://docs.google.com/spreadsheets/d/1bE3h0ZCqPAUhW6Gn6G0fKEoOPdopGTZnmmWK1VuVurI/edit

**Comment by vashmata** [comment]
> Physical View v1.0
> 
> ![image](https://user-images.githubusercontent.com/18620025/94348364-83bf7380-0009-11eb-9976-142c8aabdc56.png)

By funnel you mean the funnel motor thing?

Does the carousel include the motor AND the limit switches? Just wondering cause you have the temperature sensors as their own thing in the diagram.

Maybe I missed it in @Laogeodritt 's doc but I don't see much about the fan control. Is it simply always on?

**Comment by vashmata** [comment]
> Class Diagram v1.0
> ![image](https://user-images.githubusercontent.com/18620025/94347959-a7cd8580-0006-11eb-9b6e-a15a7acb6b97.png)

The pumps wouldn't have PID control based on the current design as we don't have a way to obtain feedback. Sorta similar for the funnel (and the carousel which isn't connected to the PID), but in this case it's cause the servos have built-in pid control that we would be able to access if we use the fancy UART commands and would have no feedback for if we use them in open loop with pwm control.

Again you haven't specified the limit switches in the carousel

**Comment by vashmata** [comment]
> > After some thought I think I should also include the list of the commands that the system should accept and their role
> 
> List of commands : https://docs.google.com/spreadsheets/d/1bE3h0ZCqPAUhW6Gn6G0fKEoOPdopGTZnmmWK1VuVurI/edit

How about checking the temperature values (in the 2-way commands)?

Even for the one-way commands, it would be nice to have a way to check if the command succeeded or failed. Either by having these commands two-way as well (responding with a success or error message), or having a command that asks for any error states and will receive a message with different types of errors (e.g. "command makes no sense," "invalid carousel position value," etc.

**Comment by MartensCedric** [comment]
> > Physical View v1.0
> > ![image](https://user-images.githubusercontent.com/18620025/94348364-83bf7380-0009-11eb-9976-142c8aabdc56.png)
> 
> By funnel you mean the funnel motor thing?
> 
> Does the carousel include the motor AND the limit switches? Just wondering cause you have the temperature sensors as their own thing in the diagram.
> 
> Maybe I missed it in @Laogeodritt 's doc but I don't see much about the fan control. Is it simply always on?

This is the physical view. It's just meant to show how the physical things are related to each other.

You have a good point that I added temp sensors but didnt mention limit switches/motors. I think im just gonna remove temp sensors for this physical view because I just wanna show how the components communicate to each other (the OBC talks with the CCD, Teensy 4.0 and Basestation, while the teensy speaks with the rest)

**Comment by MartensCedric** [comment]
> > Class Diagram v1.0
> > ![image](https://user-images.githubusercontent.com/18620025/94347959-a7cd8580-0006-11eb-9b6e-a15a7acb6b97.png)
> 
> The pumps wouldn't have PID control based on the current design as we don't have a way to obtain feedback. Sorta similar for the funnel (and the carousel which isn't connected to the PID), but in this case it's cause the servos have built-in pid control that we would be able to access if we use the fancy UART commands and would have no feedback for if we use them in open loop with pwm control.

So for the pump, we're just using a timer and don't care about PID control? So what uses a PID then? Does the fans use one to control temperature? If not ill just remove the whole PidController
> 
> Again you haven't specified the limit switches in the carousel

**Comment by MartensCedric** [comment]
> > > After some thought I think I should also include the list of the commands that the system should accept and their role
> > 
> > 
> > List of commands : https://docs.google.com/spreadsheets/d/1bE3h0ZCqPAUhW6Gn6G0fKEoOPdopGTZnmmWK1VuVurI/edit
> 
> How about checking the temperature values (in the 2-way commands)?
Yes true, I'll add it. Thanks!
> 
> Even for the one-way commands, it would be nice to have a way to check if the command succeeded or failed. Either by having these commands two-way as well (responding with a success or error message), or having a command that asks for any error states and will receive a message with different types of errors (e.g. "command makes no sense," "invalid carousel position value," etc.

Yes, I could put every command in the Two-Way category. We should consult with @Laogeodritt though

**Comment by vashmata** [comment]
this reminds me of something else, the science teensy could also keep a log of errors and timestamps for us to pull up later. Same with temperature readings or other data. Since it only responds when we poll it we're probably missing lots of info that may be useful

**Comment by vashmata** [comment]
> > > Class Diagram v1.0
> > > ![image](https://user-images.githubusercontent.com/18620025/94347959-a7cd8580-0006-11eb-9b6e-a15a7acb6b97.png)
> > 
> > 
> > The pumps wouldn't have PID control based on the current design as we don't have a way to obtain feedback. Sorta similar for the funnel (and the carousel which isn't connected to the PID), but in this case it's cause the servos have built-in pid control that we would be able to access if we use the fancy UART commands and would have no feedback for if we use them in open loop with pwm control.
> 
> So for the pump, we're just using a timer and don't care about PID control? So what uses a PID then? Does the fans use one to control temperature? If not ill just remove the whole PidController

Not sure about the fans... @Laogeodritt ? But for everything else I don't think it's needed.
> 
> > Again you haven't specified the limit switches in the carousel
> 
> Yes good point

**Comment by MartensCedric** [comment]
> this reminds me of something else, the science teensy could also keep a log of errors and timestamps for us to pull up later. Same with temperature readings or other data. Since it only responds when we poll it we're probably missing lots of info that may be useful

Yes, I think this is out of scope of science since it would have to be implemented on every teensy right

**Comment by MartensCedric** [comment]
v2.0
![image](https://user-images.githubusercontent.com/18620025/95660079-75865280-0af3-11eb-98f7-51b5684c0a1e.png)

**Comment by MartensCedric** [comment]
Deployment diagram v2
The purpose of this is just so you can understand what is connected to what device (obc does CCD stuff) while the rest is on the teensy. Not meant to show what has limit switches or whatever
![image](https://user-images.githubusercontent.com/18620025/95660949-39ee8700-0af9-11eb-84fe-e1e03edd620c.png)

**Comment by vashmata** [comment]
> Deployment diagram v2
> The purpose of this is just so you can understand what is connected to what device (obc does CCD stuff) while the rest is on the teensy. Not meant to show what has limit switches or whatever
> ![image](https://user-images.githubusercontent.com/18620025/95660949-39ee8700-0af9-11eb-84fe-e1e03edd620c.png)

the fan's purpose is to cool the laser assembly, up to you if you wanna keep them separate but i would put them next to each other on this diagram

**Comment by MartensCedric** [comment]
> > Deployment diagram v2
> > The purpose of this is just so you can understand what is connected to what device (obc does CCD stuff) while the rest is on the teensy. Not meant to show what has limit switches or whatever
> > ![image](https://user-images.githubusercontent.com/18620025/95660949-39ee8700-0af9-11eb-84fe-e1e03edd620c.png)
> 
> the fan's purpose is to cool the laser assembly, up to you if you wanna keep them separate but i would put them next to each other on this diagram

Honestly this diagram is just to show that the OBC controls the CCD and the teensy controls the rest. It's not really meant to show the interaction between the components. Its just so someone doesnt think we are doing CCD stuff in the teensy or using the OBC for the pump.

**Comment by MartensCedric** [comment]
What about the class diagram @vashmata ?

**Comment by vashmata** [comment]
I don't think I have anything more to say, personally I might want to make it explicit that within the carousel you're interacting with limit switches because it's an electrical interface, but that's on you
