### ISSUE TITLE
Define a message format

### ISSUE THREAD

**Issue by MartensCedric** [space-concordia-robotics/robotics-prototype#498]
A definition of the message format should be defined. A google docs should be created (This one can be updated : https://docs.google.com/spreadsheets/u/1/d/1bE3h0ZCqPAUhW6Gn6G0fKEoOPdopGTZnmmWK1VuVurI/edit?usp=drive_web&ouid=111054195812684486479)

The message format should tell us exactly what information is contained, the sheet should make sure that we have the information of the command ID of each command, their description, arguments, argument type etc. So that other members can easily refer to that sheet.

**Comment by ginywiny** [comment]
Created a very basic draft just to make a simple idea. Would need others to give their thoughts.

**Comment by VimFreeman** [comment]
I added some comments
We should meet anyways today at some point

**Comment by ginywiny** [comment]
Created the Rover and Science formats with @VimFreeman and @MartensCedric. PDS and arm commands message format have yet to be done.
