### ISSUE TITLE
[Everyone] Add info to readme

### ISSUE THREAD

**Issue by kcamcam** [space-concordia-robotics/robotics-prototype#5]
Maybe we could add a list of the different software teams and members with github tags, so we can better communicate/document? 
**Example:**  
#### Team Leads:  
- Peter[@PeterGhimself](https://github.com/PeterGhimself)

#### Motor-Interface:  
- Kevin [@kcamcam](https://github.com/kcamcam)
- Josh [@CraniumField](https://github.com/CraniumField)

**Comment by PeterGhimself** [comment]
started work on branch [update-read-me-5](/space-concordia-robotics/robotics-prototype/tree/update-read-me-5)

**Comment by Davidster** [comment]
good idea
