### ISSUE TITLE
CCD software on Ubuntu (Raman)

### ISSUE THREAD

**Issue by MartensCedric** [space-concordia-robotics/robotics-prototype#512]
Linear CCD Raman Spec Sheet : https://www.thorlabs.com/newgrouppage9.cfm?objectgroup_id=5290

Software to download :  https://www.thorlabs.com/software_pages/ViewSoftwarePage.cfm?Code=SPLICCO

To finish this issue, make it work on Ubuntu.  If you can't get it to run, we need to figure out a plan get it integrated with the system.

**Comment by VimFreeman** [comment]
@steamypotato Same here, can we get the data we need using the jetson?

**Comment by steamypotato** [comment]
@VimFreeman yes, but I never wrote a proper ros node for it, i might do that if its not too much of an annoyance. also i had only tested it on Koa's computer, not the jetson (but I will if we can connect it)
