### ISSUE TITLE
NIR Software Ubuntu

### ISSUE THREAD

**Issue by MartensCedric** [space-concordia-robotics/robotics-prototype#513]
https://www.ti.com/tool/DLPNIRNANOEVM

To close this issue, this software should work on Ubuntu. If you can't get it to run, we need to figure out a plan get it integrated with the system.

**Comment by KoaTheKoala** [comment]
Found this link that might be useful: https://e2e.ti.com/support/dlp/f/94/p/847597/3141022?tisearch=e2e-sitesearch&keymatch=DLPNIRNANOEVM%20linux#3141022

**Comment by MartensCedric** [comment]
You might be able to avoid running the software, make a C++ ROS node and use what is described  https://www.ti.com/tool/DLPNIRNANOEVM#software

**Comment by VimFreeman** [comment]
@steamypotato Do we have a working way of interfacing with the NIR over the Jetson?

**Comment by steamypotato** [comment]
@VimFreeman the NIR was done in C++ , so either we created a C++ ros node, or do some weird python-c wrapping thing that some people do. This was only tested on my PC not the jetson

**Comment by VimFreeman** [comment]
A C++ is perfectly fine. We can get someone to test it if the code is complete
