### ISSUE TITLE
IMU sensor arduino

### ISSUE THREAD

**Issue by PeterGhimself** [space-concordia-robotics/robotics-prototype#53]
Test board:
- [x] Setup the gyroscope and obtain data from it (GY-89).
- [x] Implement gyroscope data processing algorithm and test it.
- [ ] Configure additional filter registers on gyroscope (GY-89).
- [x] Setup the accelerometer and obtain data from it (GY-89).
- [x] Implement accelerometer data processing algorithm and test it.
- [ ] Configure additional filter registers on accelerometer (GY-89).
- [x] Setup the magnetometer and obtain data from it (GY-89).
- [ ] Implement magnetometer data processing algorithm and test it.
- [ ] Configure additional filter registers on magnetometer (GY-89).

Final board:
- [ ] Setup the sensors and obtain data (code similar to GY-89).
- [ ] Process data and verify its correctness.
- [ ] Configure additional filter registers.
- [ ] Implement Kalman filter.

**Comment by PhilCarPi** [comment]
Started development on branch [imu-sensor-arduino](/space-concordia-robotics/robotics-prototype/tree/imu-sensor-arduino-53)

**Comment by dansavin** [comment]
Added the main code for test IMU on branch [imu-main-code-53](/space-concordia-robotics/robotics-prototype/tree/imu-main-code-53)

**Comment by PeterGhimself** [comment]
Closing via #122
