### ISSUE TITLE
Absolute encoder Teensy code

### ISSUE THREAD

**Issue by steamypotato** [space-concordia-robotics/robotics-prototype#552]
Joshua is about to finish implementing the PLD for the 3 wire to 4 wire SPI bridge for the absolute magnetic encoder. The Teensy will interface with the PLD, and treat the peripheral as a standard 4 wire SPI, letting the PLD handle the rest. Relevant checks to be done are : 

[ ] CRC match between master and slave
[ ] Redundancy check of measured values
[ ] Read angle and angular speed data

Model of encoder is TLE5012B

**Comment by vexandmore** [comment]
stale
