### ISSUE TITLE
Combine CommsNode.py and CommsNodeLocalTest.py into one file

### ISSUE THREAD

**Issue by VimFreeman** [space-concordia-robotics/robotics-prototype#562]
We should be able to launch the same file with a parameter dictating whether it should run over serial on the TX2 or over USB locally.

**Comment by PaoloFer** [comment]
hi, I would like to try to solve this issue, and I wanted to ask for a clarification:
In this refactoring task, the goal is to bring together CommsNodeLocalTest.py and CommsNode.py in a single file
and the only difference is the fact of local execution if I am not misunderstood.

**Comment by RealWilliamWells** [comment]
I ended up addressing this doing the ROS2 migration effort. Will close this issue when migration is finalized

**Comment by vexandmore** [comment]
I ended up doing this in pr #606
