### ISSUE TITLE
Arm IK control algorithm

### ISSUE THREAD

**Issue by RealWilliamWells** [space-concordia-robotics/robotics-prototype#579]
This will be a new control system that uses the solved IK formulas in order to provide simplier control for the arm. This is to be paired with the CAD mouse driver.
Tasks:
- [x] 3D mouse
- [ ] IK solver
- [ ] Code that simulates motors and absolute encoders

**Comment by RealWilliamWells** [comment]
![image](https://user-images.githubusercontent.com/55707515/202049932-6b6aa40a-7544-46e3-a1b0-7093be5d6925.png)

New formulas that could be used for velocity based control system created by Daniel

**Comment by vexandmore** [comment]
Blocked by absolute encoders simulation
