### ISSUE TITLE
Better manual wheel control in controller node

### ISSUE THREAD

**Issue by RealWilliamWells** [space-concordia-robotics/robotics-prototype#580]
Currently the manual wheel control scheme using our controller node does not allow operators to easily turn the rover while driving in one direction. This is something can be addressed as part of the current controller node.

Location of controller node for mapping inputs to ROS commands: https://github.com/space-concordia-robotics/robotics-prototype/blob/master/robot/rospackages/src/mcu_control/src/joy_comms_control.cpp
(There is also a header file in mcu_control/include)

**Comment by vexandmore** [comment]
stale, I fixed this
