### ISSUE TITLE
New motor driver with CAN bus implementation into MobilePlatform

### ISSUE THREAD

**Issue by VimFreeman** [space-concordia-robotics/robotics-prototype#591]
Our new motor drivers are CAN bus enabled and we need to add code to the wheel teensy to control them.
protocol details can be found [here](https://docs.revrobotics.com/sparkmax/gs-sm)

**Comment by RealWilliamWells** [comment]
CAN protocol for BLDC driver is closed source, so it would need to be reversed engineered

**Comment by vexandmore** [comment]
Keeping, if a new member is willing to do it
