### ISSUE TITLE
ROS2 Migration

### ISSUE THREAD

**Issue by RealWilliamWells** [space-concordia-robotics/robotics-prototype#594]
The mcu_control package should be migrated entirely over to ROS2.

The following nodes must be migrated over:
- [x] CommsNode
- [x] JoyCommsControl
- [ ] ~~MarkerNode~~
- [x] Anything else relevent for current rover and arm control

The following third party related applications must be confirm as working as well:
- [x] cv_camera_node for rover camera streams
- [x] AR tag detection with at least aruco tags working
- [x] ROS2 wrappers for 3D Lidar and ZED2 camera

Then the README and environment setup must be migrated over:
- [x] Update ROS install script to install ROS 2 instead
- [x] Update systemd service to startup ROS 2 rover launch file

Passing criterial for task:
- [x] Successful on board test of updated CommsNode for operating Wheels and Arm with dualshock 4 controller
- [ ] Camera streams from rover
- [ ] 3D Lidar and ZED2 camera working as expected on board
- [ ] ~~Aruco AR tag detection on board~~
- [x] ROS2 rover startup sequence working reilability

This orginally wasn't going to be a thing this year but going to try to hammer this out ASAP. As the benefits gain from making this change will greatly benefit us immediately.

**Comment by vexandmore** [comment]
Need to re migrate CommsNode and JoyCommsControl for URC changes
