### ISSUE TITLE
ROS2 3D Lidar driver setup

### ISSUE THREAD

**Issue by RealWilliamWells** [space-concordia-robotics/robotics-prototype#610]
For ROS Humble, we want to have the drivers in place to be able to use the sensors for autonomy. 

## Acceptance
- [x] 3D Lidar is able to be setup with the use of scripts and ROS processes to be usable in RViz2.

This does not need to be functional yet on the OBC, especially that we intend to replace it so efforts are better focused later.

**Comment by vutung3196** [comment]
Reference https://www.stereolabs.com/docs/ros2/
