### ISSUE TITLE
ROS2 ZED2 Driver

### ISSUE THREAD

**Issue by RealWilliamWells** [space-concordia-robotics/robotics-prototype#617]
For ROS Humble, we want to have the drivers in place to be able to use the sensors for autonomy. 

## Acceptance
- [ ] [ZED2](https://github.com/stereolabs/zed-ros2-wrapper) is able to be setup with the use of scripts and ROS processes to be usable in RViz2. 

This does not need to be functional yet on the OBC, especially that we intend to replace it so efforts are better focused later.

**Comment by vutung3196** [comment]
branch out from ros-migration

**Comment by RealWilliamWells** [comment]
You can add any dependencies necessary to robot/rospackages/third-party-dependencies.repos

**Comment by vutung3196** [comment]
Hey @RealWilliamWells , I can't find the branch rostwo-migration anymore. Can you help me with this?

**Comment by RealWilliamWells** [comment]
Hello, the branch is rostwo-migration-594. You can find it here: https://github.com/space-concordia-robotics/robotics-prototype/tree/rostwo-migration-594

Are you about to checkout to it locally? `git checkout rostwo-migration-594`
