### ISSUE TITLE
Lidar experimentation

### ISSUE THREAD

**Issue by tatumalenko** [space-concordia-robotics/robotics-prototype#63]
**Getting our LIDAR incorporation started!**

The goal at hand is to start out by experimenting with the current LIDAR device we have, the LIDAR Lite V3. This will help assess the basic needs involved in incorporating a LIDAR component into the robot's design, specifically how to operate it with the end goal of automated self-driving capability.

Upon getting the LIDAR unit, there was no data cable included with it so I ordered one from RobotShop and will start the actual development shortly.

**Comment by tatumalenko** [comment]
Started development on branch [lidar-experimentation-63](/space-concordia-robotics/robotics-prototype/tree/lidar-experimentation-63)

**Comment by tatumalenko** [comment]
Found some likely useful ROS links:
* https://gitlab.iri.upc.edu/asantamaria/LidarLite
* https://github.com/raultron/lidar-lite-v3-ros
* https://github.com/cocasema/ros-lidar-lite

**Comment by PeterGhimself** [comment]
@KoaTheKoala closing this issue as it has been stale for a long time, but I do suggest that you or Mina take a look at this if you which to see what work was done before using the Lidar lite v3 module
