### ISSUE TITLE
Refactor/Reimplement joy controller 

### ISSUE THREAD

**Issue by steamypotato** [space-concordia-robotics/robotics-prototype#631]
In the old repo, joy controller package would publish to the command topics for the wheels and arm, using the string protocol. However, since the abolishment of that protocol, that package is overly complicated for our purposes, and is in need of refactored (package in question : https://github.com/space-concordia-robotics/robotics-prototype/tree/master/robot/rospackages/src/joy_control). 
Current needs to support only the ps4 controller (to be expanded in the future?), and publish to the wheels and arm velocities topics, instead of wheels_command and arm_commands. Thus
- [ ] Remove joy subscribers from arm_controller_node and wheels_controller_node
- [ ] Publish to cmd_vel (wheels velocities) and arm_values (arm velocities) from joy_controller_node

**Comment by vexandmore** [comment]
Obsoleted by #634
