### ISSUE TITLE
ROS Inverse Kinematics demo

### ISSUE THREAD

**Issue by PeterGhimself** [space-concordia-robotics/robotics-prototype#66]
## Description
Implementing a demo to test ROS inverse kinematics libraries.

## Sources:
[ROS tutorial series for URDF](http://wiki.ros.org/urdf/Tutorials/Building%20a%20Visual%20Robot%20Model%20with%20URDF%20from%20Scratch)

## TODO
- [ ] Create URDF model of arm
- [ ] Test and select adequate library for IK
- [ ] Implement demo

**Comment by PeterGhimself** [comment]
Work started on branch [ros-ik-demo-66](/space-concordia-robotics/robotics-prototype/tree/ros-ik-demo-66)

**Comment by Mkaller** [comment]
Can I repurpose this issue for my own needs? We would need to forget about ROS for now, but otherwise I will be working on similar things

**Comment by PeterGhimself** [comment]
@Mkaller leave this issue be and create a new (more generic) one instead please.

**Comment by PeterGhimself** [comment]
Closing via #132
