### ISSUE TITLE
[MCUR1] Rover skid steering serial

### ISSUE THREAD

**Issue by PeterGhimself** [space-concordia-robotics/robotics-prototype#71]
MCUR1 = Micro Controller Unit Rover 1 

Getting the rover teensy in a state of moving the rover wheels based of incoming serial input cmds.

**Comment by tatumalenko** [comment]
Started development on branch [rover-skid-steering-71](/space-concordia-robotics/robotics-prototype/tree/rover-skid-steering-71).

**Comment by vashmata** [comment]
Closed via #107
