### ISSUE TITLE
[MCUS1] Drill control

### ISSUE THREAD

**Issue by PeterGhimself** [space-concordia-robotics/robotics-prototype#84]
- [x] Arduino code written for controlling two DC motors
- [x] Rosify code above
- [x] Integrate with GUI

**Comment by PeterGhimself** [comment]
cosing via #86

**Comment by vashmata** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Test turntable through GUI](https://trello.com/c/Yo3vsijE/83-test-turntable-through-gui)

**Comment by vashmata** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Test Drill Controls](https://trello.com/c/F2CF07CD/82-test-drill-controls)
