### ISSUE TITLE
Rover page

### ISSUE THREAD

**Issue by PeterGhimself** [space-concordia-robotics/robotics-prototype#85]
Wireframe:
![mobile_platform_view](https://user-images.githubusercontent.com/19865282/52548072-6472c480-2d99-11e9-9819-c25acef31525.PNG)

**Comment by tatumalenko** [comment]
What it looks like so far:
![image](https://user-images.githubusercontent.com/6502401/52845355-e550f980-30d4-11e9-999a-614a21524048.png)
