### ISSUE TITLE
Tennis Ball Detection

### ISSUE THREAD

**Issue by PeterGhimself** [space-concordia-robotics/robotics-prototype#93]
Given there is already some code that detects objects:

- [x] calculate the intrinsic and distortion matrices (because of wide-angle lens of camera)
- [x] detect centroid of objects
- [x] modify code to detect tennis balls
- [ ] distance detection of objects (based off focal length)
- - [ ] obtain focal length value of sjcam4000 camera for calculations
- [x] Obtain distance of tennis ball from center of screen
- [ ] Test building/running on Ubuntu 16.04

Resources:
- [Manual for sjcam4000](https://sjcam.com/wp-content/uploads/2017/05/SJ4000-EN-MANUAL-2017_v2.1-f1.4.pdf)

**Comment by MartensCedric** [comment]
Closed sinice it is no longer a requirement
