### ISSUE TITLE
Rover gazebo simulation

### ISSUE THREAD

**Issue by PeterGhimself** [space-concordia-robotics/robotics-prototype#95]
- [x] Import CAD model from SolidWorks into gazebo (result: urdf file)
- [x] Re-test and get to work on Ubuntu 16.04 (instead of VM)
- [ ] Implement publisher/subscriber nodes for simulating wheel movement based off encoder data/wheel velocities
- [x] (optional) optimize for performance so that can be run with less issues on hardware challenged lab computers
- [ ] ~~Embed into our GUI (if feasible, otherwise keep as separate process)~~

**Comment by PeterGhimself** [comment]
@vashmata @alihessami is this still being worked on by either of you? I'm guessing it's on hold

**Comment by vashmata** [comment]
Yeah, it's on hold currently.
