### ISSUE TITLE
Integrate ROS directly inside of GUI

### ISSUE THREAD

**Issue by vashmata** [space-concordia-robotics/robotics-prototype#99]
This issue is continued by issue #105
### Modify webpage to use ROS directly instead of using workarounds
- [x] Refactor app.py, app.js, etc for general control
- - [x] Add battery voltage calc in Teensy code and display it in GUI
- - [x] Implement requests to services (mux selector, serial commands, task handler)
besides serial commands if listener is not active
- - [x] Implement parameters to directly control local vs competition and usb vs uart inside the webpage? 
- - - [x] Arguments to ArmNode.py control usb vs uart
- - - [x] Control usb vs uart in webpage? use parameters? or task_handler args?
- [x] Refactor app.py, arm.js and Arm.html for arm control
- - [x] Rename AsimovOperation.html to Arm.html
- - [x] Activate ArmNode.py with task_handler instead of arm_listener
- - [x] Implement requests to services (ping, etc - generic)
- - [x] Implement publishing to topics (stop, budge, reset, etc - generic)
- - [x] Handle multiple keypresses for simultaneous budging
- - [x] Implement subscribing to topics (listen for arm angles and update the gui - and other messages?)
- - [x] Update manual controls GUI to be more intuitive
- - [x] Add open/closed loop button
- - [x] Add speed adjustment control
- - [x] Implement homing call 
- [x] Implement protections dealing with serial commands and mux channels ex. arm page:
- - [x] listener is off - serial commands can pick any mux channel and send any serial command using generic thing which opens and closes usb port
- - [x] try to turn listener on - will check if on arm channel. if not attempts to go to arm channel, if can't doesn't turn on. if yes attempts to turn listener on
- - [x] listener is on - refuse to go to other channels and send arm commands
### Build a ROS package for interfacing with Arm Teensy
- [x] Finish making arm node to interface correctly between teensy and ROS
- - [x] Publish messages from teensy to relevant topics
- - - [x] Publish any messages to topics
- - - [x] Deal with newline stripping bug
- - - [x] Filter messages and decide where to publish different types
- - - - [x] Figure out teensy comms to make this easier
- - - [x] Decide where to split up angle messages into distinct topics, consider making composite messages for angles/budge commands/move commands etc
- - [x] Subscribe and respond to commands
- - [x] Respond to client requests
- - - [x] Create or find a .srv file which sends a String and responds with a String (the response) and a bool (indicating success or failure)
- - [x] Refine serial comms code
- - - [ ] ~~Make serial class to easily interface with serial port either via usb or uart~~ (future refactor)
- - - [x] Implement timeout for serial response during service callback and serial feedback during subscriber callbacks
- - - [x] Remove latency on opening serial comms for node
- - - - [x] Implement timeout for listening for feedback
- - - - [x] replace 3 attempts with better logic

### Add helpful files
- [x] Add guidelines for starting up the ros websockets server along with app.py
- [x] Make a demo webpage which interfaces with ROS
- [x] Update the readme

**Comment by PeterGhimself** [comment]
You can check out the [.srv](https://github.com/space-concordia-robotics/robotics-prototype/blob/master/robot/rospackages/src/ping_acknowledgment/srv/PingResponse.srv) file from the ping_acknowledgment package I wrote. It's just missing the boolean in the response.

**Comment by PeterGhimself** [comment]
Closing via #102
